namespace JueMingZ.Automation.Search
{
    internal static partial class ItemContainerOpenSourceIndex
    {
        private static ContainerDefinition[] CreateBossBagDefinitions()
        {
            return new[]
            {
                BossBag("KingSlimeBossBag", 3318, "王者史莱姆宝藏袋",
                    Output("RoyalGel", 3090, "必出"),
                    Output("NinjaHood", 256, "可能开出"),
                    Output("NinjaShirt", 257, "可能开出"),
                    Output("NinjaPants", 258, "可能开出"),
                    Output("SlimeGun", 2610, "可能开出"),
                    Output("SlimeHook", 2585, "可能开出"),
                    Output("Solidifier", 998, "必出"),
                    Output("SlimySaddle", 2430, "可能开出"),
                    Output("KingSlimeMask", 2493, "可能开出"),
                    Output("SlimeStaff", 1309, "可能开出")),

                BossBag("EyeOfCthulhuBossBag", 3319, "克苏鲁之眼宝藏袋",
                    Output("EoCShield", 3097, "必出"),
                    Output("DemoniteOre", 56, "也可由宝藏袋开出"),
                    Output("CrimtaneOre", 880, "也可由宝藏袋开出"),
                    Output("CorruptSeeds", 59, "可能开出"),
                    Output("CrimsonSeeds", 2171, "可能开出"),
                    Output("UnholyArrow", 47, "可能开出"),
                    Output("EyeMask", 2112, "可能开出"),
                    Output("Binoculars", 1299, "可能开出")),

                BossBag("EaterOfWorldsBossBag", 3320, "世界吞噬怪宝藏袋",
                    Output("WormScarf", 3224, "必出"),
                    Output("DemoniteOre", 56, "也可由宝藏袋开出"),
                    Output("ShadowScale", 86, "也可由宝藏袋开出"),
                    Output("EatersBone", 994, "可能开出"),
                    Output("EaterMask", 2111, "可能开出")),

                BossBag("BrainOfCthulhuBossBag", 3321, "克苏鲁之脑宝藏袋",
                    Output("BrainOfConfusion", 3223, "必出"),
                    Output("CrimtaneOre", 880, "也可由宝藏袋开出"),
                    Output("TissueSample", 1329, "也可由宝藏袋开出"),
                    Output("BrainMask", 2104, "可能开出"),
                    Output("BoneRattle", 3060, "可能开出")),

                BossBag("QueenBeeBossBag", 3322, "蜂后宝藏袋",
                    Output("HiveBackpack", 3333, "必出"),
                    Output("BeeGun", 1121, "可能开出"),
                    Output("BeeKeeper", 1123, "可能开出"),
                    Output("BeesKnees", 2888, "可能开出"),
                    Output("HoneyComb", 1132, "可能开出"),
                    Output("Nectar", 1170, "可能开出"),
                    Output("HoneyedGoggles", 2502, "可能开出"),
                    Output("QueenOfBees", 5483, "可能开出"),
                    Output("HiveWand", 1129, "必出"),
                    Output("BeeHat", 842, "可能开出"),
                    Output("BeeShirt", 843, "可能开出"),
                    Output("BeePants", 844, "可能开出"),
                    Output("Beenade", 1130, "可能开出"),
                    Output("BeeWax", 2431, "可能开出"),
                    Output("QueenBeeMask", 2108, "可能开出")),

                BossBag("SkeletronBossBag", 3323, "骷髅王宝藏袋",
                    Output("BoneGlove", 3245, "必出"),
                    Output("SkeletronMask", 1281, "可能开出"),
                    Output("SkeletronHand", 1273, "可能开出"),
                    Output("BookofSkulls", 1313, "可能开出")),

                BossBag("WallOfFleshBossBag", 3324, "血肉墙宝藏袋",
                    Output("DemonHeart", 3335, "未拥有时必出"),
                    Output("Pwnhammer", 367, "必出"),
                    Output("WarriorEmblem", 490, "可能开出"),
                    Output("SorcererEmblem", 489, "可能开出"),
                    Output("RangerEmblem", 491, "可能开出"),
                    Output("SummonerEmblem", 2998, "可能开出"),
                    Output("LaserRifle", 514, "可能开出"),
                    Output("BreakerBlade", 426, "可能开出"),
                    Output("ClockworkAssaultRifle", 434, "可能开出"),
                    Output("FireWhip", 4912, "可能开出"),
                    Output("WallOfFleshMask", 2105, "可能开出")),

                BossBag("QueenSlimeBossBag", 4957, "史莱姆皇后宝藏袋",
                    Output("VolatileGelatin", 4987, "必出"),
                    Output("GelBalloon", 4986, "可能开出"),
                    Output("QueenSlimeMountSaddle", 4981, "可能开出"),
                    Output("Smolstar", 4758, "可能开出"),
                    Output("QueenSlimeHook", 4980, "可能开出"),
                    Output("CrystalNinjaHelmet", 4982, "可能开出"),
                    Output("CrystalNinjaChestplate", 4983, "可能开出"),
                    Output("CrystalNinjaLeggings", 4984, "可能开出"),
                    Output("QueenSlimeMask", 4959, "可能开出")),

                BossBag("DestroyerBossBag", 3325, "毁灭者宝藏袋",
                    Output("MechanicalWagonPiece", 3355, "必出"),
                    Output("SoulofMight", 548, "也可由宝藏袋开出"),
                    Output("HallowedBar", 1225, "也可由宝藏袋开出"),
                    Output("DestroyerMask", 2113, "可能开出")),

                BossBag("TwinsBossBag", 3326, "双子魔眼宝藏袋",
                    Output("MechanicalWheelPiece", 3354, "必出"),
                    Output("SoulofSight", 549, "也可由宝藏袋开出"),
                    Output("HallowedBar", 1225, "也可由宝藏袋开出"),
                    Output("TwinMask", 2106, "可能开出")),

                BossBag("SkeletronPrimeBossBag", 3327, "机械骷髅王宝藏袋",
                    Output("MechanicalBatteryPiece", 3356, "必出"),
                    Output("SoulofFright", 547, "也可由宝藏袋开出"),
                    Output("HallowedBar", 1225, "也可由宝藏袋开出"),
                    Output("SkeletronPrimeMask", 2107, "可能开出")),

                BossBag("PlanteraBossBag", 3328, "世纪之花宝藏袋",
                    Output("SporeSac", 3336, "必出"),
                    Output("TempleKey", 1141, "必出"),
                    Output("Seedling", 1182, "可能开出"),
                    Output("TheAxe", 1305, "可能开出"),
                    Output("PygmyStaff", 1157, "可能开出"),
                    Output("ThornHook", 3021, "可能开出"),
                    Output("GrenadeLauncher", 758, "可能开出"),
                    Output("RocketI", 771, "可能开出"),
                    Output("VenusMagnum", 1255, "可能开出"),
                    Output("NettleBurst", 788, "可能开出"),
                    Output("LeafBlower", 1178, "可能开出"),
                    Output("FlowerPow", 1259, "可能开出"),
                    Output("WaspGun", 1155, "可能开出"),
                    Output("Seedler", 3018, "可能开出"),
                    Output("FlowerWhip", 5477, "可能开出"),
                    Output("PlanteraMask", 2109, "可能开出")),

                BossBag("GolemBossBag", 3329, "魔像宝藏袋",
                    Output("ShinyStone", 3337, "必出"),
                    Output("BeetleHusk", 2218, "也可由宝藏袋开出"),
                    Output("Picksaw", 1294, "可能开出"),
                    Output("Stynger", 1258, "可能开出"),
                    Output("StyngerBolt", 1261, "可能开出"),
                    Output("PossessedHatchet", 1122, "可能开出"),
                    Output("SunStone", 899, "可能开出"),
                    Output("EyeoftheGolem", 1248, "可能开出"),
                    Output("HeatRay", 1295, "可能开出"),
                    Output("StaffofEarth", 1296, "可能开出"),
                    Output("GolemFist", 1297, "可能开出"),
                    Output("GolemMask", 2110, "可能开出")),

                BossBag("FishronBossBag", 3330, "猪龙鱼公爵宝藏袋",
                    Output("ShrimpyTruffle", 3367, "必出"),
                    Output("FishronWings", 2609, "可能开出"),
                    Output("FlaironFlail", 5526, "可能开出"),
                    Output("Tsunami", 2624, "可能开出"),
                    Output("RazorbladeTyphoon", 2622, "可能开出"),
                    Output("TempestStaff", 2621, "可能开出"),
                    Output("EelWhip", 5478, "可能开出"),
                    Output("BubbleGun", 2623, "可能开出"),
                    Output("DukeFishronMask", 2588, "可能开出")),

                BossBag("CultistBossBag", 3331, "拜月教邪教徒宝藏袋",
                    Output("BossMaskCultist", 3372, "可能开出")),

                BossBag("MoonLordBossBag", 3332, "月亮领主宝藏袋",
                    Output("PortalGun", 3384, "未拥有时必出"),
                    Output("LunarOre", 3460, "也可由宝藏袋开出"),
                    Output("GravityGlobe", 1131, "必出"),
                    Output("SuspiciousLookingTentacle", 3577, "必出"),
                    Output("LongRainbowTrailWings", 4954, "必出"),
                    Output("Meowmere", 3063, "武器池抽取 2 件"),
                    Output("Terrarian", 3389, "武器池抽取 2 件"),
                    Output("StarWrath", 3065, "武器池抽取 2 件"),
                    Output("SDMG", 1553, "武器池抽取 2 件"),
                    Output("Celeb2", 3930, "武器池抽取 2 件"),
                    Output("LastPrism", 3541, "武器池抽取 2 件"),
                    Output("LunarFlareBook", 3570, "武器池抽取 2 件"),
                    Output("RainbowCrystalStaff", 3571, "武器池抽取 2 件"),
                    Output("MoonlordTurretStaff", 3569, "武器池抽取 2 件"),
                    Output("MoonLordWhip", 5480, "武器池抽取 2 件"),
                    Output("MeowmereMinecart", 4469, "可能开出"),
                    Output("BossMaskMoonlord", 3373, "可能开出")),

                BossBag("FairyQueenBossBag", 4782, "光之女皇宝藏袋",
                    Output("EmpressFlightBooster", 4989, "必出"),
                    Output("PiercingStarlight", 4923, "可能开出"),
                    Output("FairyQueenMagicItem", 4952, "可能开出"),
                    Output("FairyQueenRangedItem", 4953, "可能开出"),
                    Output("RainbowWhip", 4914, "可能开出"),
                    Output("SparkleGuitar", 4715, "可能开出"),
                    Output("RainbowWings", 4823, "可能开出"),
                    Output("HallowBossDye", 4778, "可能开出"),
                    Output("RainbowCursor", 5075, "可能开出"),
                    Output("FairyQueenMask", 4784, "可能开出")),

                BossBag("DeerclopsBossBag", 5111, "鹿角怪宝藏袋",
                    Output("BoneHelm", 5100, "必出"),
                    Output("ChesterPetItem", 5098, "可能开出"),
                    Output("Eyebrella", 5101, "可能开出"),
                    Output("DontStarveShaderItem", 5113, "可能开出"),
                    Output("PewMaticHorn", 5117, "可能开出"),
                    Output("WeatherPain", 5118, "可能开出"),
                    Output("HoundiusShootius", 5119, "可能开出"),
                    Output("LucyTheAxe", 5095, "可能开出"),
                    Output("DizzyHat", 5385, "可能开出"),
                    Output("DeerclopsMask", 5109, "可能开出")),

                BossBag("BossBagBetsy", 3860, "双足翼龙宝藏袋",
                    Output("DD2BetsyBow", 3859, "可能开出"),
                    Output("DD2SquireBetsySword", 3827, "可能开出"),
                    Output("ApprenticeStaffT3", 3870, "可能开出"),
                    Output("MonkStaffT3", 3858, "可能开出"),
                    Output("BetsyWings", 3883, "可能开出"),
                    Output("BossMaskBetsy", 3863, "可能开出"))
            };
        }
    }
}
