namespace JueMingZ.Automation.Search
{
    internal static partial class ItemFishingSourceIndex
    {
        private static SourceDefinition[] CreateFishingDropDefinitions()
        {
            return new[]
            {
                Fish("Bass", 2290, "普通鱼获", "普通水域", "鱼获候选", "常见水域鱼获；不预测当前水域或渔力"),
                Fish("Trout", 2297, "普通鱼获", "海洋水域", "鱼获候选", "海洋水域鱼获；不预测当前水域"),
                Fish("Salmon", 2298, "普通鱼获", "大水域", "鱼获候选", "大面积水域鱼获；不预测当前水域"),
                Fish("AtlanticCod", 2299, "普通鱼获", "雪地水域", "鱼获候选", "雪地水域鱼获；不预测当前水域"),
                Fish("Tuna", 2300, "普通鱼获", "海洋水域", "鱼获候选", "海洋水域鱼获；不预测当前水域"),
                Fish("RedSnapper", 2301, "普通鱼获", "海洋水域", "鱼获候选", "海洋水域鱼获；不预测当前水域"),
                Fish("NeonTetra", 2302, "普通鱼获", "丛林水域", "鱼获候选", "丛林水域鱼获；不预测当前水域"),
                Fish("Shrimp", 2316, "普通鱼获", "海洋水域", "鱼获候选", "海洋水域鱼获；不预测当前水域"),

                Fish("Rockfish", 2320, "环境鱼获", "地下/洞穴水域", "鱼获候选", "地下或洞穴高度鱼获；不预测当前水域或渔力"),
                Fish("ArmoredCavefish", 2303, "环境鱼获", "地下/洞穴水域", "鱼获候选", "地下或洞穴水域常见；不展示完整概率"),
                Fish("SpecularFish", 2309, "环境鱼获", "地下/洞穴水域", "鱼获候选", "地下、洞穴或雪地地下水域鱼获；不展示完整概率"),
                Fish("Stinkfish", 2321, "环境鱼获", "地下/洞穴水域", "鱼获候选", "地下或洞穴水域鱼获；不预测当前水域"),
                Fish("FrostMinnow", 2306, "环境鱼获", "雪地水域", "鱼获候选", "雪地环境水域常见；不预测当前水域"),
                Fish("PrincessFish", 2307, "环境鱼获", "神圣水域", "鱼获候选", "神圣环境水域常见；不预测当前世界条件"),
                Fish("Prismite", 2310, "环境鱼获", "神圣水域", "鱼获候选", "神圣环境水域鱼获；不预测当前世界条件"),
                Fish("ChaosFish", 2317, "环境鱼获", "地下神圣水域", "鱼获候选", "地下或洞穴神圣水域鱼获；不预测当前世界条件"),
                Fish("Ebonkoi", 2318, "环境鱼获", "腐化水域", "鱼获候选", "腐化环境水域鱼获；不预测当前世界邪恶"),
                Fish("PurpleClubberfish", 2330, "环境鱼获", "腐化水域", "鱼获候选", "腐化环境水域鱼获；不预测当前世界邪恶"),
                Fish("Hemopiranha", 2319, "环境鱼获", "猩红水域", "鱼获候选", "猩红环境水域常见；不预测当前世界邪恶"),
                Fish("CrimsonTigerfish", 2305, "环境鱼获", "猩红水域", "鱼获候选", "猩红环境水域鱼获；不预测当前世界邪恶"),
                Fish("VariegatedLardfish", 2311, "环境鱼获", "地下丛林水域", "鱼获候选", "地下或洞穴丛林水域鱼获；不预测当前水域"),
                Fish("DoubleCod", 2313, "环境鱼获", "丛林水域", "鱼获候选", "丛林水域鱼获；不预测当前水域"),
                Fish("Damselfish", 2304, "环境鱼获", "天空湖", "鱼获候选", "天空湖鱼获；不预测当前高度"),
                Fish("GoldenCarp", 2308, "稀有鱼获", "地表以下水域", "鱼获候选", "地表以下水域稀有鱼获；不展示完整概率"),
                Fish("Honeyfin", 2314, "特殊鱼获", "蜂蜜水域", "鱼获候选", "蜂蜜钓鱼鱼获；不预测当前液体"),
                Fish("FlarefinKoi", 2312, "特殊鱼获", "熔岩钓鱼", "鱼获候选", "熔岩钓鱼鱼获；需要可熔岩钓鱼条件"),
                Fish("Obsidifish", 2315, "特殊鱼获", "熔岩钓鱼", "鱼获候选", "熔岩钓鱼鱼获；需要可熔岩钓鱼条件"),
                Fish("Swordfish", 2332, "特殊鱼获", "海洋水域", "鱼获候选", "海洋水域鱼获；不展示完整概率"),
                Fish("ReaverShark", 2341, "特殊鱼获", "海洋水域", "鱼获候选", "海洋水域鱼获；不展示完整概率"),
                Fish("SawtoothShark", 2342, "特殊鱼获", "海洋水域", "鱼获候选", "海洋水域鱼获；不展示完整概率"),
                Fish("ObsidianSwordfish", 2331, "特殊鱼获", "熔岩钓鱼", "鱼获候选", "熔岩困难模式鱼获候选；不展示完整概率"),
                Fish("AlchemyTable", 3000, "地牢鱼获", "地牢水域", "鱼获候选", "地牢钓鱼直接鱼获；不预测当前水域或渔力"),
                Fish("BewitchingTable", 2999, "地牢鱼获", "地牢水域", "鱼获候选", "地牢钓鱼直接鱼获；不预测当前水域或渔力"),

                FishingCrate("WoodenCrate", 2334, "普通钓鱼", "普通宝匣，可由钓鱼获得"),
                FishingCrate("WoodenCrateHard", 3979, "困难模式普通钓鱼", "普通困难模式宝匣，可由钓鱼获得"),
                FishingCrate("IronCrate", 2335, "普通钓鱼", "普通宝匣，可由钓鱼获得"),
                FishingCrate("IronCrateHard", 3980, "困难模式普通钓鱼", "普通困难模式宝匣，可由钓鱼获得"),
                FishingCrate("GoldenCrate", 2336, "普通钓鱼", "普通宝匣，可由钓鱼获得"),
                FishingCrate("GoldenCrateHard", 3981, "困难模式普通钓鱼", "普通困难模式宝匣，可由钓鱼获得"),
                FishingCrate("CorruptFishingCrate", 3203, "腐化水域钓鱼", "腐化环境宝匣，可由钓鱼获得"),
                FishingCrate("CorruptFishingCrateHard", 3982, "困难模式腐化水域钓鱼", "腐化困难模式宝匣，可由钓鱼获得"),
                FishingCrate("CrimsonFishingCrate", 3204, "猩红水域钓鱼", "猩红环境宝匣，可由钓鱼获得"),
                FishingCrate("CrimsonFishingCrateHard", 3983, "困难模式猩红水域钓鱼", "猩红困难模式宝匣，可由钓鱼获得"),
                FishingCrate("DungeonFishingCrate", 3205, "地牢钓鱼", "地牢钓鱼宝匣，可由钓鱼获得"),
                FishingCrate("DungeonFishingCrateHard", 3984, "困难模式地牢钓鱼", "地牢困难模式宝匣，可由钓鱼获得"),
                FishingCrate("FloatingIslandFishingCrate", 3206, "天空湖钓鱼", "天空湖钓鱼宝匣，可由钓鱼获得"),
                FishingCrate("FloatingIslandFishingCrateHard", 3985, "困难模式天空湖钓鱼", "天空湖困难模式宝匣，可由钓鱼获得"),
                FishingCrate("HallowedFishingCrate", 3207, "神圣水域钓鱼", "神圣环境宝匣，可由钓鱼获得"),
                FishingCrate("HallowedFishingCrateHard", 3986, "困难模式神圣水域钓鱼", "神圣困难模式宝匣，可由钓鱼获得"),
                FishingCrate("JungleFishingCrate", 3208, "丛林钓鱼", "丛林钓鱼宝匣，可由钓鱼获得"),
                FishingCrate("JungleFishingCrateHard", 3987, "困难模式丛林钓鱼", "丛林困难模式宝匣，可由钓鱼获得"),
                FishingCrate("FrozenCrate", 4405, "雪地钓鱼", "雪地钓鱼宝匣，可由钓鱼获得"),
                FishingCrate("FrozenCrateHard", 4406, "困难模式雪地钓鱼", "雪地困难模式宝匣，可由钓鱼获得"),
                FishingCrate("OasisCrate", 4407, "沙漠绿洲钓鱼", "绿洲钓鱼宝匣，可由钓鱼获得"),
                FishingCrate("OasisCrateHard", 4408, "困难模式沙漠绿洲钓鱼", "绿洲困难模式宝匣，可由钓鱼获得"),
                FishingCrate("OceanCrate", 5002, "海洋钓鱼", "海洋钓鱼宝匣，可由钓鱼获得"),
                FishingCrate("OceanCrateHard", 5003, "困难模式海洋钓鱼", "海洋困难模式宝匣，可由钓鱼获得"),
                FishingCrate("LavaCrate", 4877, "熔岩钓鱼", "熔岩钓鱼宝匣，可由钓鱼获得"),
                FishingCrate("LavaCrateHard", 4878, "困难模式熔岩钓鱼", "熔岩困难模式宝匣，可由钓鱼获得"),

                QuestFish("Bunnyfish", 2479, "森林地表水域", "地表水域任务鱼"),
                QuestFish("BumblebeeTuna", 2451, "蜂蜜水域", "蜂蜜钓鱼任务鱼"),
                QuestFish("Dirtfish", 2455, "森林地表/地下水域", "地表或地下浅层任务鱼"),
                QuestFish("DynamiteFish", 2456, "地表水域", "地表水域任务鱼"),
                QuestFish("ZombieFish", 2474, "地表水域", "地表水域任务鱼"),
                QuestFish("Bonefish", 2478, "地下/洞穴水域", "地下或洞穴任务鱼"),
                QuestFish("Batfish", 2450, "地下/洞穴水域", "地下或洞穴任务鱼"),
                QuestFish("Jewelfish", 2464, "地下/洞穴水域", "地下或洞穴任务鱼"),
                QuestFish("Spiderfish", 2469, "地下/洞穴水域", "地下或洞穴任务鱼"),
                QuestFish("Hungerfish", 2462, "洞穴/地狱附近水域", "更深层级任务鱼"),
                QuestFish("DemonicHellfish", 2482, "洞穴/地狱附近水域", "更深层级任务鱼"),
                QuestFish("GuideVoodooFish", 2472, "洞穴/地狱附近水域", "更深层级任务鱼"),
                QuestFish("Fishotron", 2460, "洞穴/地狱附近水域", "更深层级任务鱼"),
                QuestFish("Slimefish", 2487, "任意水域", "通用任务鱼"),
                QuestFish("Harpyfish", 2461, "天空湖/高空水域", "高空任务鱼"),
                QuestFish("Cloudfish", 2453, "天空湖", "天空湖任务鱼"),
                QuestFish("Wyverntail", 2473, "天空湖", "天空湖任务鱼"),
                QuestFish("Angelfish", 2476, "天空湖", "天空湖任务鱼"),
                QuestFish("FallenStarfish", 2458, "高空/天空湖水域", "高空任务鱼"),
                QuestFish("TheFishofCthulu", 2459, "高空/天空湖水域", "高空任务鱼"),
                QuestFish("Catfish", 2452, "丛林地表水域", "丛林任务鱼"),
                QuestFish("Derpfish", 2483, "丛林地表水域", "丛林任务鱼"),
                QuestFish("TropicalBarracuda", 2488, "丛林地表水域", "丛林任务鱼"),
                QuestFish("Mudfish", 2486, "丛林地下/洞穴水域", "丛林任务鱼"),
                QuestFish("Pengfish", 2467, "雪地地表/高空水域", "雪地任务鱼"),
                QuestFish("TundraTrout", 2470, "雪地地表水域", "雪地任务鱼"),
                QuestFish("Fishron", 2484, "雪地地下/洞穴水域", "雪地任务鱼"),
                QuestFish("MutantFlinxfin", 2466, "雪地地下/洞穴水域", "雪地任务鱼"),
                QuestFish("Pixiefish", 2468, "神圣地表/高空水域", "神圣任务鱼"),
                QuestFish("MirageFish", 2465, "神圣地下/洞穴水域", "神圣任务鱼"),
                QuestFish("UnicornFish", 2471, "神圣水域", "神圣任务鱼"),
                QuestFish("Cursedfish", 2454, "腐化水域", "腐化任务鱼"),
                QuestFish("InfectedScabbardfish", 2485, "腐化水域", "腐化任务鱼"),
                QuestFish("EaterofPlankton", 2457, "腐化水域", "腐化任务鱼"),
                QuestFish("BloodyManowar", 2477, "猩红水域", "猩红任务鱼"),
                QuestFish("Ichorfish", 2463, "猩红水域", "猩红任务鱼"),
                QuestFish("CapnTunabeard", 2480, "海洋水域", "海洋任务鱼"),
                QuestFish("Clownfish", 2481, "海洋水域", "海洋任务鱼"),
                QuestFish("AmanitaFungifin", 2475, "发光蘑菇水域", "发光蘑菇环境任务鱼")
            };
        }
    }
}
