namespace JueMingZ.Automation.Search
{
    internal static partial class ItemContainerOpenSourceIndex
    {
        private static ContainerDefinition[] CreateGenericOpenContainerDefinitions()
        {
            return new[]
            {
                OpenContainer("HerbBag", 3093, "草药袋",
                    Output("Daybloom", 313, "可能开出"),
                    Output("Moonglow", 314, "可能开出"),
                    Output("Blinkroot", 315, "可能开出"),
                    Output("Deathweed", 316, "可能开出"),
                    Output("Waterleaf", 317, "可能开出"),
                    Output("Fireblossom", 318, "可能开出"),
                    Output("Shiverthorn", 2358, "可能开出"),
                    Output("DaybloomSeeds", 307, "可能开出"),
                    Output("MoonglowSeeds", 308, "可能开出"),
                    Output("BlinkrootSeeds", 309, "可能开出"),
                    Output("DeathweedSeeds", 310, "可能开出"),
                    Output("WaterleafSeeds", 311, "可能开出"),
                    Output("FireblossomSeeds", 312, "可能开出"),
                    Output("ShiverthornSeeds", 2357, "可能开出")),

                OpenContainer("GoodieBag", 1774, "礼袋",
                    Output("UnluckyYarn", 1810, "稀有可能开出"),
                    Output("BatHook", 1800, "稀有可能开出"),
                    Output("RottenEgg", 1809, "可能开出 10-40 个"),
                    Output("JackingSkeletron", 1846, "装饰画候选"),
                    Output("BitterHarvest", 1847, "装饰画候选"),
                    Output("BloodMoonCountess", 1848, "装饰画候选"),
                    Output("HallowsEve", 1849, "装饰画候选"),
                    Output("MorbidCuriosity", 1850, "装饰画候选"),
                    Output("CatMask", 1749, "服装套装池"),
                    Output("CatShirt", 1750, "服装套装池"),
                    Output("CatPants", 1751, "服装套装池"),
                    Output("CreeperMask", 1746, "服装套装池"),
                    Output("CreeperShirt", 1747, "服装套装池"),
                    Output("CreeperPants", 1748, "服装套装池"),
                    Output("GhostMask", 1752, "服装套装池"),
                    Output("GhostShirt", 1753, "服装套装池"),
                    Output("LeprechaunHat", 1767, "服装套装池"),
                    Output("LeprechaunShirt", 1768, "服装套装池"),
                    Output("LeprechaunPants", 1769, "服装套装池"),
                    Output("PixieShirt", 1770, "服装套装池"),
                    Output("PixiePants", 1771, "服装套装池"),
                    Output("PrincessHat", 1772, "服装套装池"),
                    Output("PrincessDressNew", 1773, "服装套装池"),
                    Output("PumpkinMask", 1754, "服装套装池"),
                    Output("PumpkinShirt", 1755, "服装套装池"),
                    Output("PumpkinPants", 1756, "服装套装池"),
                    Output("RobotMask", 1757, "服装套装池"),
                    Output("RobotShirt", 1758, "服装套装池"),
                    Output("RobotPants", 1759, "服装套装池"),
                    Output("UnicornMask", 1760, "服装套装池"),
                    Output("UnicornShirt", 1761, "服装套装池"),
                    Output("UnicornPants", 1762, "服装套装池"),
                    Output("VampireMask", 1763, "服装套装池"),
                    Output("VampireShirt", 1764, "服装套装池"),
                    Output("VampirePants", 1765, "服装套装池"),
                    Output("WitchHat", 1766, "服装套装池"),
                    Output("WitchDress", 1775, "服装套装池"),
                    Output("WitchBoots", 1776, "服装套装池"),
                    Output("BrideofFrankensteinMask", 1777, "服装套装池"),
                    Output("BrideofFrankensteinDress", 1778, "服装套装池"),
                    Output("KarateTortoiseMask", 1779, "服装套装池"),
                    Output("KarateTortoiseShirt", 1780, "服装套装池"),
                    Output("KarateTortoisePants", 1781, "服装套装池"),
                    Output("ReaperHood", 1819, "服装套装池"),
                    Output("ReaperRobe", 1820, "服装套装池"),
                    Output("FoxMask", 1821, "服装套装池"),
                    Output("FoxShirt", 1822, "服装套装池"),
                    Output("FoxPants", 1823, "服装套装池"),
                    Output("CatEars", 1824, "可能开出"),
                    Output("SpaceCreatureMask", 1838, "服装套装池"),
                    Output("SpaceCreatureShirt", 1839, "服装套装池"),
                    Output("SpaceCreaturePants", 1840, "服装套装池"),
                    Output("WolfMask", 1841, "服装套装池"),
                    Output("WolfShirt", 1842, "服装套装池"),
                    Output("WolfPants", 1843, "服装套装池"),
                    Output("TreasureHunterShirt", 1851, "服装套装池"),
                    Output("TreasureHunterPants", 1852, "服装套装池"))
            };
        }
    }
}
