using System;
using JueMingZ.Actions;
using JueMingZ.Automation.AutoRecovery;
using JueMingZ.Automation.Combat;
using JueMingZ.Automation.Fishing;
using JueMingZ.Automation.Information;
using JueMingZ.Automation.InventoryAndItems;
using JueMingZ.Automation.Movement;
using JueMingZ.Automation.NpcServices;
using JueMingZ.Automation.WorldAutomation;
using JueMingZ.Bootstrap;
using JueMingZ.Common;
using JueMingZ.Compat;
using JueMingZ.Config;
using JueMingZ.Diagnostics;
using JueMingZ.Features;
using JueMingZ.GameState;
using JueMingZ.Input;
using JueMingZ.UI;
using JueMingZ.UI.Information;
using JueMingZ.UI.Legacy;

namespace JueMingZ.Runtime
{
    internal static partial class RuntimeDiagnosticSnapshotBuilder
    {
        private static void WriteMovement(DiagnosticSnapshot snapshot, RuntimeDiagnosticSnapshotSource source)
        {
            var simulatedJump = MovementSimulatedJumpService.GetDiagnostics();
            var continuousDash = MovementContinuousDashService.GetDiagnostics();
            var teleportCorrection = MovementTeleportCorrectionService.GetDiagnostics();
            var safeLanding = MovementSafeLandingService.GetDiagnostics();

            snapshot.MovementSimulatedJumpEnabled = simulatedJump != null && simulatedJump.Enabled;
            snapshot.MovementSimulatedJumpLastTriggered = simulatedJump != null && simulatedJump.LastTriggered;
            snapshot.MovementSimulatedJumpLastTriggerUtc = simulatedJump == null ? null : simulatedJump.LastTriggerUtc;
            snapshot.MovementSimulatedJumpLastDecision = simulatedJump == null ? string.Empty : simulatedJump.LastDecision;
            snapshot.MovementSimulatedJumpLastSkipReason = simulatedJump == null ? string.Empty : simulatedJump.LastSkipReason;
            snapshot.MovementSimulatedJumpLastDecisionUtc = simulatedJump == null ? null : simulatedJump.LastDecisionUtc;
            snapshot.MovementSimulatedJumpLastTick = simulatedJump == null ? 0 : simulatedJump.LastTick;
            snapshot.MovementSimulatedJumpPendingActionCount = simulatedJump == null ? 0 : simulatedJump.PendingActionCount;
            snapshot.MovementSimulatedJumpRunningActionKind = simulatedJump == null ? string.Empty : simulatedJump.RunningActionKind;
            snapshot.MovementSimulatedJumpItemUseBridgeBusy = simulatedJump != null && simulatedJump.ItemUseBridgeBusy;
            snapshot.MovementSimulatedJumpTextInputFocused = simulatedJump != null && simulatedJump.TextInputFocused;
            snapshot.MovementSimulatedJumpTextInputReason = simulatedJump == null ? string.Empty : simulatedJump.TextInputReason;
            snapshot.MovementSimulatedJumpHeld = simulatedJump != null && simulatedJump.JumpHeld;
            snapshot.MovementSimulatedJumpDownHeld = simulatedJump != null && simulatedJump.DownHeld;
            snapshot.MovementSimulatedJumpPlayerControllable = simulatedJump != null && simulatedJump.PlayerControllable;
            snapshot.MovementSimulatedJumpAvailableOpportunity = simulatedJump != null && simulatedJump.AvailableJumpOpportunity;
            snapshot.MovementSimulatedJumpGroundedOrSliding = simulatedJump != null && simulatedJump.GroundedOrSliding;
            snapshot.MovementSimulatedJumpAerialWindow = simulatedJump != null && simulatedJump.AerialJumpWindow;
            snapshot.MovementSimulatedJumpHasAirJump = simulatedJump != null && simulatedJump.HasAirJump;
            snapshot.MovementSimulatedJumpHasRocketJump = simulatedJump != null && simulatedJump.HasRocketJump;
            snapshot.MovementSimulatedJumpHasWingFlight = simulatedJump != null && simulatedJump.HasWingFlight;
            snapshot.MovementSimulatedJumpMountActive = simulatedJump != null && simulatedJump.MountActive;
            snapshot.MovementSimulatedJumpMountCanFlyKnown = simulatedJump != null && simulatedJump.MountCanFlyKnown;
            snapshot.MovementSimulatedJumpMountCanFly = simulatedJump != null && simulatedJump.MountCanFly;
            snapshot.MovementSimulatedJumpCapabilitySummary = simulatedJump == null ? string.Empty : simulatedJump.CapabilitySummary;
            snapshot.MovementSimulatedJumpSubmittedCount = simulatedJump == null ? 0 : simulatedJump.SubmittedCount;
            snapshot.MovementSimulatedJumpSkippedCount = simulatedJump == null ? 0 : simulatedJump.SkippedCount;
            snapshot.MovementContinuousDashEnabled = continuousDash != null && continuousDash.Enabled;
            snapshot.MovementContinuousDashMode = continuousDash == null ? string.Empty : continuousDash.Mode;
            snapshot.MovementContinuousDashLastTriggered = continuousDash != null && continuousDash.LastTriggered;
            snapshot.MovementContinuousDashLastTriggerDirection = continuousDash == null ? 0 : continuousDash.LastTriggerDirection;
            snapshot.MovementContinuousDashLastTriggerUtc = continuousDash == null ? null : continuousDash.LastTriggerUtc;
            snapshot.MovementContinuousDashLastDecision = continuousDash == null ? string.Empty : continuousDash.LastDecision;
            snapshot.MovementContinuousDashLastSkipReason = continuousDash == null ? string.Empty : continuousDash.LastSkipReason;
            snapshot.MovementContinuousDashLastDecisionUtc = continuousDash == null ? null : continuousDash.LastDecisionUtc;
            snapshot.MovementContinuousDashLastTick = continuousDash == null ? 0 : continuousDash.LastTick;
            snapshot.MovementContinuousDashPendingActionCount = continuousDash == null ? 0 : continuousDash.PendingActionCount;
            snapshot.MovementContinuousDashRunningActionKind = continuousDash == null ? string.Empty : continuousDash.RunningActionKind;
            snapshot.MovementContinuousDashTextInputFocused = continuousDash != null && continuousDash.TextInputFocused;
            snapshot.MovementContinuousDashTextInputReason = continuousDash == null ? string.Empty : continuousDash.TextInputReason;
            snapshot.MovementContinuousDashPlayerControllable = continuousDash != null && continuousDash.PlayerControllable;
            snapshot.MovementContinuousDashLeftHeld = continuousDash != null && continuousDash.LeftHeld;
            snapshot.MovementContinuousDashRightHeld = continuousDash != null && continuousDash.RightHeld;
            snapshot.MovementContinuousDashHeldDirection = continuousDash == null ? 0 : continuousDash.HeldDirection;
            snapshot.MovementContinuousDashHasDashAbility = continuousDash != null && continuousDash.HasDashAbility;
            snapshot.MovementContinuousDashAbilitySource = continuousDash == null ? string.Empty : continuousDash.DashAbilitySource;
            snapshot.MovementContinuousDashDashType = continuousDash == null ? 0 : continuousDash.DashType;
            snapshot.MovementContinuousDashDashDelay = continuousDash == null ? 0 : continuousDash.DashDelay;
            snapshot.MovementContinuousDashCooldownReady = continuousDash != null && continuousDash.DashCooldownReady;
            snapshot.MovementContinuousDashMountActive = continuousDash != null && continuousDash.MountActive;
            snapshot.MovementContinuousDashMountType = continuousDash == null ? -1 : continuousDash.MountType;
            snapshot.MovementContinuousDashMountCanDashKnown = continuousDash != null && continuousDash.MountCanDashKnown;
            snapshot.MovementContinuousDashMountCanDash = continuousDash != null && continuousDash.MountCanDash;
            snapshot.MovementContinuousDashCapabilitySummary = continuousDash == null ? string.Empty : continuousDash.CapabilitySummary;
            snapshot.MovementContinuousDashArmedDirection = continuousDash == null ? 0 : continuousDash.ArmedDirection;
            snapshot.MovementContinuousDashArmedCancelReason = continuousDash == null ? string.Empty : continuousDash.ArmedCancelReason;
            snapshot.MovementContinuousDashArmedCancelCount = continuousDash == null ? 0 : continuousDash.ArmedCancelCount;
            snapshot.MovementContinuousDashHookInstalled = continuousDash != null && continuousDash.DashMovementHookInstalled;
            snapshot.MovementContinuousDashHookMessage = continuousDash == null ? string.Empty : continuousDash.DashMovementHookMessage;
            snapshot.MovementContinuousDashQueuedPulsePending = continuousDash != null && continuousDash.QueuedPulsePending;
            snapshot.MovementContinuousDashLastPulseApplied = continuousDash != null && continuousDash.LastPulseApplied;
            snapshot.MovementContinuousDashLastPulseDirection = continuousDash == null ? 0 : continuousDash.LastPulseDirection;
            snapshot.MovementContinuousDashLastPulseUtc = continuousDash == null ? null : continuousDash.LastPulseUtc;
            snapshot.MovementContinuousDashLastPulseMessage = continuousDash == null ? string.Empty : continuousDash.LastPulseMessage;
            snapshot.MovementContinuousDashLastPulseWasFallback = continuousDash != null && continuousDash.LastPulseWasFallback;
            snapshot.MovementContinuousDashLastPulseResetMessage = continuousDash == null ? string.Empty : continuousDash.LastPulseResetMessage;
            snapshot.MovementContinuousDashLastCompatError = continuousDash == null ? string.Empty : continuousDash.LastCompatError;
            snapshot.MovementContinuousDashSubmittedCount = continuousDash == null ? 0 : continuousDash.SubmittedCount;
            snapshot.MovementContinuousDashSkippedCount = continuousDash == null ? 0 : continuousDash.SkippedCount;
            snapshot.MovementTeleportCorrectionEnabled = teleportCorrection != null && teleportCorrection.Enabled;
            snapshot.MovementTeleportCorrectionHookInstalled = teleportCorrection != null && teleportCorrection.HookInstalled;
            snapshot.MovementTeleportCorrectionHookMethod = teleportCorrection == null ? string.Empty : teleportCorrection.HookMethod;
            snapshot.MovementTeleportCorrectionHookMessage = teleportCorrection == null ? string.Empty : teleportCorrection.HookMessage;
            snapshot.MovementTeleportCorrectionLastDecision = teleportCorrection == null ? string.Empty : teleportCorrection.LastDecision;
            snapshot.MovementTeleportCorrectionLastSkipReason = teleportCorrection == null ? string.Empty : teleportCorrection.LastSkipReason;
            snapshot.MovementTeleportCorrectionLastDecisionUtc = teleportCorrection == null ? null : teleportCorrection.LastDecisionUtc;
            snapshot.MovementTeleportCorrectionItemType = teleportCorrection == null ? 0 : teleportCorrection.ItemType;
            snapshot.MovementTeleportCorrectionItemName = teleportCorrection == null ? string.Empty : teleportCorrection.ItemName;
            snapshot.MovementTeleportCorrectionOriginalMouseWorldX = teleportCorrection == null ? 0d : teleportCorrection.OriginalMouseWorldX;
            snapshot.MovementTeleportCorrectionOriginalMouseWorldY = teleportCorrection == null ? 0d : teleportCorrection.OriginalMouseWorldY;
            snapshot.MovementTeleportCorrectionOriginalMouseScreenX = teleportCorrection == null ? -1 : teleportCorrection.OriginalMouseScreenX;
            snapshot.MovementTeleportCorrectionOriginalMouseScreenY = teleportCorrection == null ? -1 : teleportCorrection.OriginalMouseScreenY;
            snapshot.MovementTeleportCorrectionOriginalTopLeftX = teleportCorrection == null ? 0d : teleportCorrection.OriginalTopLeftX;
            snapshot.MovementTeleportCorrectionOriginalTopLeftY = teleportCorrection == null ? 0d : teleportCorrection.OriginalTopLeftY;
            snapshot.MovementTeleportCorrectionOriginalSafe = teleportCorrection != null && teleportCorrection.OriginalSafe;
            snapshot.MovementTeleportCorrectionSearchRadiusPixels = teleportCorrection == null ? 0 : teleportCorrection.SearchRadiusPixels;
            snapshot.MovementTeleportCorrectionSearchStepPixels = teleportCorrection == null ? 0 : teleportCorrection.SearchStepPixels;
            snapshot.MovementTeleportCorrectionCandidateCount = teleportCorrection == null ? 0 : teleportCorrection.CandidateCount;
            snapshot.MovementTeleportCorrectionValidCandidateCount = teleportCorrection == null ? 0 : teleportCorrection.ValidCandidateCount;
            snapshot.MovementTeleportCorrectionNearestCandidateDistance = teleportCorrection == null ? 0d : teleportCorrection.NearestCandidateDistance;
            snapshot.MovementTeleportCorrectionCorrectedTopLeftX = teleportCorrection == null ? 0d : teleportCorrection.CorrectedTopLeftX;
            snapshot.MovementTeleportCorrectionCorrectedTopLeftY = teleportCorrection == null ? 0d : teleportCorrection.CorrectedTopLeftY;
            snapshot.MovementTeleportCorrectionCorrectedMouseWorldX = teleportCorrection == null ? 0d : teleportCorrection.CorrectedMouseWorldX;
            snapshot.MovementTeleportCorrectionCorrectedMouseWorldY = teleportCorrection == null ? 0d : teleportCorrection.CorrectedMouseWorldY;
            snapshot.MovementTeleportCorrectionCorrectedMouseScreenX = teleportCorrection == null ? -1 : teleportCorrection.CorrectedMouseScreenX;
            snapshot.MovementTeleportCorrectionCorrectedMouseScreenY = teleportCorrection == null ? -1 : teleportCorrection.CorrectedMouseScreenY;
            snapshot.MovementTeleportCorrectionMouseCaptureSucceeded = teleportCorrection != null && teleportCorrection.MouseCaptureSucceeded;
            snapshot.MovementTeleportCorrectionMouseApplySucceeded = teleportCorrection != null && teleportCorrection.MouseApplySucceeded;
            snapshot.MovementTeleportCorrectionMouseRestoreSucceeded = teleportCorrection != null && teleportCorrection.MouseRestoreSucceeded;
            snapshot.MovementTeleportCorrectionVanillaContinued = teleportCorrection != null && teleportCorrection.VanillaContinued;
            snapshot.MovementTeleportCorrectionLastCompatError = teleportCorrection == null ? string.Empty : teleportCorrection.LastCompatError;
            snapshot.MovementTeleportCorrectionAppliedCount = teleportCorrection == null ? 0 : teleportCorrection.AppliedCount;
            snapshot.MovementTeleportCorrectionSkippedCount = teleportCorrection == null ? 0 : teleportCorrection.SkippedCount;
            snapshot.MovementSafeLandingEnabled = safeLanding != null && safeLanding.Enabled;
            snapshot.MovementSafeLandingLastTriggered = safeLanding != null && safeLanding.LastTriggered;
            snapshot.MovementSafeLandingLastTriggerUtc = safeLanding == null ? null : safeLanding.LastTriggerUtc;
            snapshot.MovementSafeLandingLastDecision = safeLanding == null ? string.Empty : safeLanding.LastDecision;
            snapshot.MovementSafeLandingLastSkipReason = safeLanding == null ? string.Empty : safeLanding.LastSkipReason;
            snapshot.MovementSafeLandingLastDecisionUtc = safeLanding == null ? null : safeLanding.LastDecisionUtc;
            snapshot.MovementSafeLandingLastTick = safeLanding == null ? 0 : safeLanding.LastTick;
            snapshot.MovementSafeLandingPendingActionCount = safeLanding == null ? 0 : safeLanding.PendingActionCount;
            snapshot.MovementSafeLandingRunningActionKind = safeLanding == null ? string.Empty : safeLanding.RunningActionKind;
            snapshot.MovementSafeLandingTextInputFocused = safeLanding != null && safeLanding.TextInputFocused;
            snapshot.MovementSafeLandingTextInputReason = safeLanding == null ? string.Empty : safeLanding.TextInputReason;
            snapshot.MovementSafeLandingPlayerControllable = safeLanding != null && safeLanding.PlayerControllable;
            snapshot.MovementSafeLandingDangerous = safeLanding != null && safeLanding.Dangerous;
            snapshot.MovementSafeLandingRescueWindow = safeLanding != null && safeLanding.RescueWindow;
            snapshot.MovementSafeLandingAlreadySafe = safeLanding != null && safeLanding.AlreadySafe;
            snapshot.MovementSafeLandingSafeReason = safeLanding == null ? string.Empty : safeLanding.SafeReason;
            snapshot.MovementSafeLandingRawCreativeGodMode = safeLanding != null && safeLanding.RawCreativeGodMode;
            snapshot.MovementSafeLandingRawNoFallDmg = safeLanding != null && safeLanding.RawNoFallDmg;
            snapshot.MovementSafeLandingRawSlowFall = safeLanding != null && safeLanding.RawSlowFall;
            snapshot.MovementSafeLandingRawWet = safeLanding != null && safeLanding.RawWet;
            snapshot.MovementSafeLandingRawHoneyWet = safeLanding != null && safeLanding.RawHoneyWet;
            snapshot.MovementSafeLandingRawShimmering = safeLanding != null && safeLanding.RawShimmering;
            snapshot.MovementSafeLandingRawWebbed = safeLanding != null && safeLanding.RawWebbed;
            snapshot.MovementSafeLandingRawStoned = safeLanding != null && safeLanding.RawStoned;
            snapshot.MovementSafeLandingRawGrapCount = safeLanding == null ? 0 : safeLanding.RawGrapCount;
            snapshot.MovementSafeLandingRawEquippedWingCount = safeLanding == null ? 0 : safeLanding.RawEquippedWingCount;
            snapshot.MovementSafeLandingRawMountNoFallDamage = safeLanding != null && safeLanding.RawMountNoFallDamage;
            snapshot.MovementSafeLandingRawExtraFall = safeLanding == null ? 0 : safeLanding.RawExtraFall;
            snapshot.MovementSafeLandingFallingSpeed = safeLanding == null ? 0d : safeLanding.FallingSpeed;
            snapshot.MovementSafeLandingVelocityY = safeLanding == null ? 0d : safeLanding.VelocityY;
            snapshot.MovementSafeLandingGravityDirection = safeLanding == null ? 0d : safeLanding.GravityDirection;
            snapshot.MovementSafeLandingImpactFound = safeLanding != null && safeLanding.ImpactFound;
            snapshot.MovementSafeLandingImpactDistancePixels = safeLanding == null ? -1 : safeLanding.ImpactDistancePixels;
            snapshot.MovementSafeLandingImpactTicks = safeLanding == null ? -1d : safeLanding.ImpactTicks;
            snapshot.MovementSafeLandingEstimatedFallTiles = safeLanding == null ? 0d : safeLanding.EstimatedFallTiles;
            snapshot.MovementSafeLandingActiveCapabilitySummary = safeLanding == null ? string.Empty : safeLanding.ActiveCapabilitySummary;
            snapshot.MovementSafeLandingSelectedStrategyId = safeLanding == null ? string.Empty : safeLanding.SelectedStrategyId;
            snapshot.MovementSafeLandingSelectedPriority = safeLanding == null ? -1 : safeLanding.SelectedPriority;
            snapshot.MovementSafeLandingSelectedActionType = safeLanding == null ? string.Empty : safeLanding.SelectedActionType;
            snapshot.MovementSafeLandingHasFlyingCarpet = safeLanding != null && safeLanding.HasFlyingCarpet;
            snapshot.MovementSafeLandingHasFlyingCarpetAvailable = safeLanding != null && safeLanding.HasFlyingCarpetAvailable;
            snapshot.MovementSafeLandingFlyingCarpetTime = safeLanding == null ? 0 : safeLanding.FlyingCarpetTime;
            snapshot.MovementSafeLandingHasGravityGlobe = safeLanding != null && safeLanding.HasGravityGlobe;
            snapshot.MovementSafeLandingHasGravityFlipOpportunity = safeLanding != null && safeLanding.HasGravityFlipOpportunity;
            snapshot.MovementSafeLandingHasEquippedFlyingMount = safeLanding != null && safeLanding.HasEquippedFlyingMount;
            snapshot.MovementSafeLandingHasEquippedSafeMount = safeLanding != null && safeLanding.HasEquippedSafeMount;
            snapshot.MovementSafeLandingHasEquippedGrapple = safeLanding != null && safeLanding.HasEquippedGrapple;
            snapshot.MovementSafeLandingHasInventoryGrapple = safeLanding != null && safeLanding.HasInventoryGrapple;
            snapshot.MovementSafeLandingHasTeleportRod = safeLanding != null && safeLanding.HasTeleportRod;
            snapshot.MovementSafeLandingTeleportRodInventorySlot = safeLanding == null ? -1 : safeLanding.TeleportRodInventorySlot;
            snapshot.MovementSafeLandingTeleportRodItemType = safeLanding == null ? 0 : safeLanding.TeleportRodItemType;
            snapshot.MovementSafeLandingTeleportTargetKnown = safeLanding != null && safeLanding.TeleportTargetKnown;
            snapshot.MovementSafeLandingTeleportTargetTileX = safeLanding == null ? -1 : safeLanding.TeleportTargetTileX;
            snapshot.MovementSafeLandingTeleportTargetTileY = safeLanding == null ? -1 : safeLanding.TeleportTargetTileY;
            snapshot.MovementSafeLandingTeleportTargetWorldX = safeLanding == null ? 0d : safeLanding.TeleportTargetWorldX;
            snapshot.MovementSafeLandingTeleportTargetWorldY = safeLanding == null ? 0d : safeLanding.TeleportTargetWorldY;
            snapshot.MovementSafeLandingGravityRestorePending = safeLanding != null && safeLanding.GravityRestorePending;
            snapshot.MovementSafeLandingGravityRestoreOriginalDirection = safeLanding == null ? 0d : safeLanding.GravityRestoreOriginalDirection;
            snapshot.MovementSafeLandingGravityRestorePendingTicks = safeLanding == null ? 0 : safeLanding.GravityRestorePendingTicks;
            snapshot.MovementSafeLandingGravityRestoreLastDecision = safeLanding == null ? string.Empty : safeLanding.GravityRestoreLastDecision;
            snapshot.MovementSafeLandingGravityRestoreLastSkipReason = safeLanding == null ? string.Empty : safeLanding.GravityRestoreLastSkipReason;
            snapshot.MovementSafeLandingConfigSummary = safeLanding == null ? string.Empty : safeLanding.ConfigSummary;
            snapshot.MovementSafeLandingStageSummary = safeLanding == null ? string.Empty : safeLanding.StageSummary;
            snapshot.MovementSafeLandingStrategyCatalogVersion = safeLanding == null ? string.Empty : safeLanding.StrategyCatalogVersion;
            snapshot.MovementSafeLandingStrategyEvaluationSummary = safeLanding == null ? string.Empty : safeLanding.StrategyEvaluationSummary;
            snapshot.MovementSafeLandingCandidateSummary = safeLanding == null ? string.Empty : safeLanding.CandidateSummary;
            snapshot.MovementSafeLandingSelectedPlanSummary = safeLanding == null ? string.Empty : safeLanding.SelectedPlanSummary;
            snapshot.MovementSafeLandingRejectedStrategiesSummary = safeLanding == null ? string.Empty : safeLanding.RejectedStrategiesSummary;
            snapshot.MovementSafeLandingPostApplyVerificationSummary = safeLanding == null ? string.Empty : safeLanding.PostApplyVerificationSummary;
            snapshot.MovementSafeLandingRecoveryStateSummary = safeLanding == null ? string.Empty : safeLanding.RecoveryStateSummary;
            snapshot.MovementSafeLandingSubmittedCount = safeLanding == null ? 0 : safeLanding.SubmittedCount;
            snapshot.MovementSafeLandingSkippedCount = safeLanding == null ? 0 : safeLanding.SkippedCount;
            snapshot.MovementSafeLandingFullAnalysisCount = safeLanding == null ? 0 : safeLanding.FullAnalysisCount;
            snapshot.MovementSafeLandingCheapPrecheckSkipCount = safeLanding == null ? 0 : safeLanding.CheapPrecheckSkipCount;
            snapshot.MovementSafeLandingLandingProbeCount = safeLanding == null ? 0 : safeLanding.LandingProbeCount;
            snapshot.MovementSafeLandingConfigSummaryCacheHitCount = safeLanding == null ? 0 : safeLanding.ConfigSummaryCacheHitCount;
            snapshot.MovementSafeLandingConfigSummaryCacheMissCount = safeLanding == null ? 0 : safeLanding.ConfigSummaryCacheMissCount;
            snapshot.MovementSafeLandingStageSummaryCacheHitCount = safeLanding == null ? 0 : safeLanding.StageSummaryCacheHitCount;
            snapshot.MovementSafeLandingCheapSkipDiagnosticSuppressedCount = safeLanding == null ? 0 : safeLanding.CheapSkipDiagnosticSuppressedCount;
            snapshot.MovementSafeLandingCheapSkipDiagnosticWrittenCount = safeLanding == null ? 0 : safeLanding.CheapSkipDiagnosticWrittenCount;
            snapshot.MovementSafeLandingCheapSkipLastReason = safeLanding == null ? string.Empty : safeLanding.CheapSkipLastReason;
            snapshot.MovementSafeLandingCheapSkipDiagnosticCadenceTicks = safeLanding == null ? 0 : safeLanding.CheapSkipDiagnosticCadenceTicks;
            snapshot.MovementSafeLandingRecoverySummarySkippedCount = safeLanding == null ? 0 : safeLanding.RecoverySummarySkippedCount;
            snapshot.MovementSafeLandingLastCompatError = safeLanding == null ? string.Empty : safeLanding.LastCompatError;
            snapshot.MovementSafeLandingCollisionFastPathStatus = safeLanding == null ? string.Empty : safeLanding.CollisionFastPathStatus ?? string.Empty;
            snapshot.MovementSafeLandingPlayerUpdateHookInstalled = safeLanding != null && safeLanding.PlayerUpdateHookInstalled;
            snapshot.MovementSafeLandingPlayerUpdateHookMessage = safeLanding == null ? string.Empty : safeLanding.PlayerUpdateHookMessage;
            snapshot.MovementSafeLandingQueuedJumpPulseActive = safeLanding != null && safeLanding.QueuedJumpPulseActive;
            snapshot.MovementSafeLandingQueuedJumpPulseStatus = safeLanding == null ? string.Empty : safeLanding.QueuedJumpPulseStatus;
            snapshot.MovementSafeLandingQueuedJumpPulseApplySite = safeLanding == null ? string.Empty : safeLanding.QueuedJumpPulseApplySite;
            snapshot.MovementSafeLandingTemporaryEquipmentApplied = safeLanding != null && safeLanding.TemporaryEquipmentApplied;
            snapshot.MovementSafeLandingTemporaryEquipmentPendingRestoreCount = safeLanding == null ? 0 : safeLanding.TemporaryEquipmentPendingRestoreCount;
            snapshot.MovementSafeLandingTemporaryEquipmentPendingRestoreNoSpaceCount = safeLanding == null ? 0 : safeLanding.TemporaryEquipmentPendingRestoreNoSpaceCount;
            snapshot.MovementSafeLandingTemporaryEquipmentLastDecision = safeLanding == null ? string.Empty : safeLanding.TemporaryEquipmentLastDecision;
            snapshot.MovementSafeLandingTemporaryEquipmentLastSkipReason = safeLanding == null ? string.Empty : safeLanding.TemporaryEquipmentLastSkipReason;
            snapshot.MovementSafeLandingTemporaryEquipmentSelectedCategory = safeLanding == null ? string.Empty : safeLanding.TemporaryEquipmentSelectedCategory;
            snapshot.MovementSafeLandingTemporaryEquipmentSelectedSourceKind = safeLanding == null ? string.Empty : safeLanding.TemporaryEquipmentSelectedSourceKind;
            snapshot.MovementSafeLandingTemporaryEquipmentSelectedSourceSlot = safeLanding == null ? -1 : safeLanding.TemporaryEquipmentSelectedSourceSlot;
            snapshot.MovementSafeLandingTemporaryEquipmentSelectedTargetKind = safeLanding == null ? string.Empty : safeLanding.TemporaryEquipmentSelectedTargetKind;
            snapshot.MovementSafeLandingTemporaryEquipmentSelectedTargetSlot = safeLanding == null ? -1 : safeLanding.TemporaryEquipmentSelectedTargetSlot;
            snapshot.MovementSafeLandingTemporaryEquipmentSelectedItemType = safeLanding == null ? 0 : safeLanding.TemporaryEquipmentSelectedItemType;
            snapshot.MovementSafeLandingTemporaryEquipmentSelectedMountType = safeLanding == null ? -1 : safeLanding.TemporaryEquipmentSelectedMountType;
            snapshot.MovementSafeLandingLandingSurfaceKnown = safeLanding != null && safeLanding.LandingSurfaceKnown;
            snapshot.MovementSafeLandingLandingContactWorldX = safeLanding == null ? 0f : safeLanding.LandingContactWorldX;
            snapshot.MovementSafeLandingLandingContactWorldY = safeLanding == null ? 0f : safeLanding.LandingContactWorldY;
            snapshot.MovementSafeLandingLandingContactTileX = safeLanding == null ? -1 : safeLanding.LandingContactTileX;
            snapshot.MovementSafeLandingLandingContactTileY = safeLanding == null ? -1 : safeLanding.LandingContactTileY;
            snapshot.MovementSafeLandingLandingSurfaceKind = safeLanding == null ? string.Empty : safeLanding.LandingSurfaceKind ?? string.Empty;
            snapshot.MovementSafeLandingLandingSlopeType = safeLanding == null ? 0 : safeLanding.LandingSlopeType;
            snapshot.MovementSafeLandingLandingSlopeDirection = safeLanding == null ? string.Empty : safeLanding.LandingSlopeDirection ?? string.Empty;
            snapshot.MovementSafeLandingLandingContactSample = safeLanding == null ? string.Empty : safeLanding.LandingContactSample ?? string.Empty;
            snapshot.MovementSafeLandingLandingMovingIntoSlope = safeLanding != null && safeLanding.LandingMovingIntoSlope;
            snapshot.MovementSafeLandingLandingMovingWithSlope = safeLanding != null && safeLanding.LandingMovingWithSlope;
            snapshot.MovementSafeLandingLandingSurfaceSummary = safeLanding == null ? string.Empty : safeLanding.LandingSurfaceSummary ?? string.Empty;
            snapshot.MovementSafeLandingGrappleHookSpeed = safeLanding == null ? 0f : safeLanding.GrappleHookSpeed;
            snapshot.MovementSafeLandingGrappleTargetSource = safeLanding == null ? string.Empty : safeLanding.GrappleTargetSource ?? string.Empty;
            snapshot.MovementSafeLandingGrappleTargetFromLandingSurface = safeLanding != null && safeLanding.GrappleTargetFromLandingSurface;
            snapshot.MovementSafeLandingGrappleTargetDistancePixels = safeLanding == null ? 0f : safeLanding.GrappleTargetDistancePixels;
            snapshot.MovementSafeLandingGrappleHookVerticalSpeed = safeLanding == null ? 0f : safeLanding.GrappleHookVerticalSpeed;
            snapshot.MovementSafeLandingGrappleRelativeDownSpeed = safeLanding == null ? 0f : safeLanding.GrappleRelativeDownSpeed;
            snapshot.MovementSafeLandingGrappleRequiredLeadTicks = safeLanding == null ? 0f : safeLanding.GrappleRequiredLeadTicks;
            snapshot.MovementSafeLandingGrappleRequiredLeadPixels = safeLanding == null ? 0 : safeLanding.GrappleRequiredLeadPixels;
            snapshot.MovementSafeLandingGrappleEstimatedTicksToTarget = safeLanding == null ? 0f : safeLanding.GrappleEstimatedTicksToTarget;
            snapshot.MovementSafeLandingGrappleTooEarly = safeLanding != null && safeLanding.GrappleTooEarly;
            snapshot.MovementSafeLandingGrappleTooLate = safeLanding != null && safeLanding.GrappleTooLate;
            snapshot.MovementSafeLandingGrappleTooSlowForDownwardSurface = safeLanding != null && safeLanding.GrappleTooSlowForDownwardSurface;
            snapshot.MovementSafeLandingGrappleTimingSummary = safeLanding == null ? string.Empty : safeLanding.GrappleTimingSummary ?? string.Empty;
            snapshot.MovementSafeLandingEquippedGrappleShootSpeed = safeLanding == null ? 0f : safeLanding.EquippedGrappleShootSpeed;
            snapshot.MovementSafeLandingInventoryGrappleShootSpeed = safeLanding == null ? 0f : safeLanding.InventoryGrappleShootSpeed;
            snapshot.MovementSafeLandingEquippedGrappleProjectileType = safeLanding == null ? 0 : safeLanding.EquippedGrappleProjectileType;
            snapshot.MovementSafeLandingInventoryGrappleProjectileType = safeLanding == null ? 0 : safeLanding.InventoryGrappleProjectileType;
            snapshot.MovementSafeLandingMaxFallSpeed = safeLanding == null ? 0f : safeLanding.MaxFallSpeed;
        }
    }
}
