using System;
using JueMingZ.Actions;
using JueMingZ.Automation.AutoRecovery;
using JueMingZ.Automation.Combat;
using JueMingZ.Automation.Fishing;
using JueMingZ.Automation.Information;
using JueMingZ.Automation.InventoryAndItems;
using JueMingZ.Automation.Movement;
using JueMingZ.Automation.NpcServices;
using JueMingZ.Automation.WorldAutomation;
using JueMingZ.Bootstrap;
using JueMingZ.Common;
using JueMingZ.Compat;
using JueMingZ.Config;
using JueMingZ.Diagnostics;
using JueMingZ.Features;
using JueMingZ.GameState;
using JueMingZ.Input;
using JueMingZ.Records;
using JueMingZ.UI;
using JueMingZ.UI.Information;
using JueMingZ.UI.Legacy;

namespace JueMingZ.Runtime
{
    internal static partial class RuntimeDiagnosticSnapshotBuilder
    {
        private static void WriteBootstrapAndGameState(DiagnosticSnapshot snapshot, RuntimeDiagnosticSnapshotSource source)
        {
            var _initialized = source.Context.Initialized;
            var Version = source.Context.Version;
            var TestRunId = source.Context.TestRunId;
            var State = source.Context.State;
            var _featureCatalogCount = source.Context.FeatureCatalogCount;
            var _implementedFeatureCount = source.Context.ImplementedFeatureCount;
            var _visibleFeatureCount = source.Context.VisibleFeatureCount;
            var _hotkeyVisibleFeatureCount = source.Context.HotkeyVisibleFeatureCount;
            var _userCategoryCounts = source.Context.UserCategoryCounts;
            var _codeDomainCounts = source.Context.CodeDomainCounts;
            var featureInfo = source.FeatureInfo;
            var gameState = source.GameState;
            var lateBootstrapCompleted = source.LateBootstrapCompleted;

            snapshot.Loaded = _initialized;
            snapshot.Version = Version;
            snapshot.RuntimeVersion = Version;
            snapshot.TestRunId = TestRunId;
            snapshot.ProcessName = GetProcessName();
            snapshot.BaseDirectory = AppDomain.CurrentDomain.BaseDirectory;
            snapshot.LogDirectory = Logger.LogDirectory;
            snapshot.TerrariaDetected = GameMode.IsTerrariaLoaded;
            snapshot.TerrariaVersion = lateBootstrapCompleted ? GameMode.GetTerrariaVersionLateOnly() : "EarlyUnavailable";
            snapshot.NetModeDescription = lateBootstrapCompleted ? GameMode.GetDescriptionLateOnly() : "EarlyUnavailable";
            snapshot.UpdateCount = State == null ? 0 : State.UpdateCount;
            snapshot.LateBootstrapCompleted = lateBootstrapCompleted;
            snapshot.SafeBootstrapStarted = AssemblyLoadTracker.SafeBootstrapStarted;
            snapshot.HarmonyLoaded = DependencyChecker.FindType("HarmonyLib.Harmony", "0Harmony") != null;
            snapshot.SafeBootstrapHookInstalled = HookDiagnostics.SafeBootstrapHookInstalled;
            snapshot.HookUpdateInstalled = HookDiagnostics.HookUpdateInstalled;
            snapshot.DrawHookInstalled = HookDiagnostics.DrawHookInstalled;
            snapshot.InterfaceLayerHookInstalled = HookDiagnostics.InterfaceLayerHookInstalled;
            snapshot.ItemCheckHookInstalled = HookDiagnostics.ItemCheckHookInstalled;
            snapshot.ItemCheckHookMethod = HookDiagnostics.ItemCheckHookMethod;
            snapshot.GoblinExecutionHookInstalled = HookDiagnostics.GoblinExecutionHookInstalled;
            snapshot.GoblinExecutionHookMethod = HookDiagnostics.GoblinExecutionHookMethod;
            snapshot.PlayerWorldDeathHookInstalled = HookDiagnostics.PlayerDeathHookInstalled;
            snapshot.PlayerWorldDeathHookMethod = HookDiagnostics.PlayerDeathHookMethod;
            snapshot.PlayerWorldDeathHookMessage = HookDiagnostics.PlayerDeathHookMessage;
            var deathDiagnostics = PlayerWorldDeathRecorder.LastDiagnostics;
            snapshot.PlayerWorldDeathLastRecordStatus = deathDiagnostics.LastRecordStatus;
            snapshot.PlayerWorldDeathLastRecordMessage = deathDiagnostics.LastRecordMessage;
            snapshot.PlayerWorldDeathLastEventId = deathDiagnostics.LastEventId;
            snapshot.PlayerWorldDeathLastPairId = deathDiagnostics.LastPairId;
            snapshot.PlayerWorldDeathLastDeathCount = deathDiagnostics.LastDeathCount;
            snapshot.PlayerWorldDeathHistoryReadFailed = deathDiagnostics.DeathHistoryReadFailed;
            var deathMarkerDiagnostics = PlayerWorldDeathMarkerDiagnostics.GetSnapshot();
            snapshot.PlayerWorldDeathMarkerLayerInstalled = deathMarkerDiagnostics.LayerInstalled;
            snapshot.PlayerWorldDeathMarkerLayerMessage = deathMarkerDiagnostics.LayerMessage;
            snapshot.PlayerWorldDeathMarkerLastStatus = deathMarkerDiagnostics.LastStatus;
            snapshot.PlayerWorldDeathMarkerLastMessage = deathMarkerDiagnostics.LastMessage;
            snapshot.PlayerWorldDeathMarkerLastPairId = deathMarkerDiagnostics.LastPairId;
            snapshot.PlayerWorldDeathMarkerCachedCount = deathMarkerDiagnostics.CachedCount;
            snapshot.PlayerWorldDeathMarkerDrawnCount = deathMarkerDiagnostics.DrawnCount;
            snapshot.PlayerWorldDeathMarkerCulledByLimit = deathMarkerDiagnostics.CulledByLimit;
            snapshot.PlayerWorldDeathMarkerHistoryReadFailed = deathMarkerDiagnostics.HistoryReadFailed;
            snapshot.PlayerWorldDeathMarkerLastDrawUtc = deathMarkerDiagnostics.LastDrawUtc;
            var deathHistoryDiagnostics = PlayerWorldDeathHistoryDiagnostics.GetSnapshot();
            snapshot.PlayerWorldDeathHistoryLastStatus = deathHistoryDiagnostics.LastStatus;
            snapshot.PlayerWorldDeathHistoryLastMessage = deathHistoryDiagnostics.LastMessage;
            snapshot.PlayerWorldDeathHistoryLastPairId = deathHistoryDiagnostics.LastPairId;
            snapshot.PlayerWorldDeathHistoryDeathCount = deathHistoryDiagnostics.DeathCount;
            snapshot.PlayerWorldDeathHistoryTotalEventCount = deathHistoryDiagnostics.TotalEventCount;
            snapshot.PlayerWorldDeathHistoryPageIndex = deathHistoryDiagnostics.PageIndex;
            snapshot.PlayerWorldDeathHistoryPageCount = deathHistoryDiagnostics.PageCount;
            snapshot.PlayerWorldDeathHistorySummaryReadFailed = deathHistoryDiagnostics.SummaryReadFailed;
            snapshot.PlayerWorldDeathHistoryPageReadFailed = deathHistoryDiagnostics.HistoryReadFailed;
            snapshot.PlayerWorldDeathHistoryLastReadUtc = deathHistoryDiagnostics.LastReadUtc;
            var playtimeDiagnostics = PlayerWorldPlaytimeDiagnostics.GetSnapshot();
            snapshot.PlayerWorldPlaytimeLastStatus = playtimeDiagnostics.LastStatus;
            snapshot.PlayerWorldPlaytimeLastMessage = playtimeDiagnostics.LastMessage;
            snapshot.PlayerWorldPlaytimeLastPairId = playtimeDiagnostics.LastPairId;
            snapshot.PlayerWorldPlaytimeTotalGameTicks = playtimeDiagnostics.TotalGameTicks;
            snapshot.PlayerWorldPlaytimeWholeDayCount = playtimeDiagnostics.WholeDayCount;
            snapshot.PlayerWorldPlaytimeReadFailed = playtimeDiagnostics.ReadFailed;
            snapshot.PlayerWorldPlaytimeWriteFailed = playtimeDiagnostics.WriteFailed;
            snapshot.PlayerWorldPlaytimeLastDeltaGameTicks = playtimeDiagnostics.LastDeltaGameTicks;
            snapshot.PlayerWorldPlaytimeLastSkippedDeltaReason = playtimeDiagnostics.LastSkippedDeltaReason;
            snapshot.PlayerWorldPlaytimeLastSampleUtc = playtimeDiagnostics.LastSampleUtc;
            snapshot.PlayerWorldPlaytimeLastWriteUtc = playtimeDiagnostics.LastWriteUtc;
            var explorationDiagnostics = PlayerWorldExplorationDiagnostics.GetSnapshot();
            snapshot.PlayerWorldExplorationLastStatus = explorationDiagnostics.LastStatus;
            snapshot.PlayerWorldExplorationLastMessage = explorationDiagnostics.LastMessage;
            snapshot.PlayerWorldExplorationLastPairId = explorationDiagnostics.LastPairId;
            snapshot.PlayerWorldExplorationWorldWidth = explorationDiagnostics.WorldWidth;
            snapshot.PlayerWorldExplorationWorldHeight = explorationDiagnostics.WorldHeight;
            snapshot.PlayerWorldExplorationTotalTileCount = explorationDiagnostics.TotalTileCount;
            snapshot.PlayerWorldExplorationRevealedTileCount = explorationDiagnostics.RevealedTileCount;
            snapshot.PlayerWorldExplorationWorkingRevealedTileCount = explorationDiagnostics.WorkingRevealedTileCount;
            snapshot.PlayerWorldExplorationScannedTileCount = explorationDiagnostics.ScannedTileCount;
            snapshot.PlayerWorldExplorationNextTileIndex = explorationDiagnostics.NextTileIndex;
            snapshot.PlayerWorldExplorationLastScannedTileBudget = explorationDiagnostics.LastScannedTileBudget;
            snapshot.PlayerWorldExplorationScanMode = explorationDiagnostics.ScanMode;
            snapshot.PlayerWorldExplorationControlState = explorationDiagnostics.ControlState;
            snapshot.PlayerWorldExplorationPausedByUser = explorationDiagnostics.PausedByUser;
            snapshot.PlayerWorldExplorationIdleComplete = explorationDiagnostics.IdleComplete;
            snapshot.PlayerWorldExplorationLastScanElapsedMs = explorationDiagnostics.LastScanElapsedMs;
            snapshot.PlayerWorldExplorationLastScanTileCount = explorationDiagnostics.LastScanTileCount;
            snapshot.PlayerWorldExplorationCurrentTimeBudgetMs = explorationDiagnostics.CurrentTimeBudgetMs;
            snapshot.PlayerWorldExplorationCurrentCadenceTicks = explorationDiagnostics.CurrentCadenceTicks;
            snapshot.PlayerWorldExplorationBackoffApplied = explorationDiagnostics.BackoffApplied;
            snapshot.PlayerWorldExplorationLastUserCommand = explorationDiagnostics.LastUserCommand;
            snapshot.PlayerWorldExplorationAutoRescanDisabled = explorationDiagnostics.AutoRescanDisabled;
            snapshot.PlayerWorldExplorationRevealedPercent = explorationDiagnostics.RevealedPercent;
            snapshot.PlayerWorldExplorationScanComplete = explorationDiagnostics.ScanComplete;
            snapshot.PlayerWorldExplorationReadFailed = explorationDiagnostics.ReadFailed;
            snapshot.PlayerWorldExplorationWriteFailed = explorationDiagnostics.WriteFailed;
            snapshot.PlayerWorldExplorationLastScanUtc = explorationDiagnostics.LastScanUtc;
            snapshot.PlayerWorldExplorationLastCompletedScanUtc = explorationDiagnostics.LastCompletedScanUtc;
            snapshot.PlayerWorldExplorationLastWriteUtc = explorationDiagnostics.LastWriteUtc;
            var mapMarkerDiagnostics = PlayerWorldMapMarkerDiagnostics.GetSnapshot();
            snapshot.PlayerWorldMapMarkersEnabled = source.SettingsSnapshot != null && source.SettingsSnapshot.MapCustomMarkersEnabled;
            snapshot.PlayerWorldMapMarkersLastStatus = mapMarkerDiagnostics.LastStatus;
            snapshot.PlayerWorldMapMarkersLastMessage = mapMarkerDiagnostics.LastMessage;
            snapshot.PlayerWorldMapMarkersLastPairId = mapMarkerDiagnostics.LastPairId;
            snapshot.PlayerWorldMapMarkersCount = mapMarkerDiagnostics.MarkerCount;
            snapshot.PlayerWorldMapMarkersReadFailed = mapMarkerDiagnostics.ReadFailed;
            snapshot.PlayerWorldMapMarkersWriteFailed = mapMarkerDiagnostics.WriteFailed;
            snapshot.PlayerWorldMapMarkersLimitExceeded = mapMarkerDiagnostics.LimitExceeded;
            snapshot.PlayerWorldMapMarkersCulledByCacheLimit = mapMarkerDiagnostics.CulledByCacheLimit;
            snapshot.PlayerWorldMapMarkersLastOperation = mapMarkerDiagnostics.LastOperation;
            snapshot.PlayerWorldMapMarkersLastUiAction = mapMarkerDiagnostics.LastUiAction;
            snapshot.PlayerWorldMapMarkersLastJumpResult = mapMarkerDiagnostics.LastJumpResult;
            snapshot.MapMarkerLastJumpRequestedTileX = mapMarkerDiagnostics.LastJumpRequestedTileX;
            snapshot.MapMarkerLastJumpRequestedTileY = mapMarkerDiagnostics.LastJumpRequestedTileY;
            snapshot.MapMarkerLastJumpWrittenMapPosX = mapMarkerDiagnostics.LastJumpWrittenMapPosX;
            snapshot.MapMarkerLastJumpWrittenMapPosY = mapMarkerDiagnostics.LastJumpWrittenMapPosY;
            snapshot.MapMarkerLastJumpScale = mapMarkerDiagnostics.LastJumpScale;
            snapshot.MapMarkerLastJumpReleasedUiCapture = mapMarkerDiagnostics.LastJumpReleasedUiCapture;
            snapshot.MapMarkerLastJumpClearedPanState = mapMarkerDiagnostics.LastJumpClearedPanState;
            snapshot.MapMarkerLastJumpConsumedButtonPulse = mapMarkerDiagnostics.LastJumpConsumedButtonPulse;
            snapshot.MapMarkerLastJumpVanillaMapInputHandoff = mapMarkerDiagnostics.LastJumpVanillaMapInputHandoff;
            snapshot.MapMarkerLastBlockedReason = mapMarkerDiagnostics.LastBlockedReason;
            snapshot.MapMarkerLastTransformRoute = mapMarkerDiagnostics.LastTransformRoute;
            snapshot.MapMarkerLastTransformScreenWidth = mapMarkerDiagnostics.LastTransformScreenWidth;
            snapshot.MapMarkerLastTransformScreenHeight = mapMarkerDiagnostics.LastTransformScreenHeight;
            snapshot.MapMarkerLastTransformMapTopLeftX = mapMarkerDiagnostics.LastTransformMapTopLeftX;
            snapshot.MapMarkerLastTransformMapTopLeftY = mapMarkerDiagnostics.LastTransformMapTopLeftY;
            snapshot.MapMarkerLastTransformScale = mapMarkerDiagnostics.LastTransformScale;
            snapshot.MapMarkerLastTransformMapFullscreenPosX = mapMarkerDiagnostics.LastTransformMapFullscreenPosX;
            snapshot.MapMarkerLastTransformMapFullscreenPosY = mapMarkerDiagnostics.LastTransformMapFullscreenPosY;
            snapshot.MapMarkerLastTransformGameUpdateCount = mapMarkerDiagnostics.LastTransformGameUpdateCount;
            snapshot.MapMarkerLastTransformUtc = mapMarkerDiagnostics.LastTransformUtc;
            snapshot.MapMarkerLastRightClickMouseX = mapMarkerDiagnostics.LastRightClickMouseX;
            snapshot.MapMarkerLastRightClickMouseY = mapMarkerDiagnostics.LastRightClickMouseY;
            snapshot.MapMarkerLastRightClickTileX = mapMarkerDiagnostics.LastRightClickTileX;
            snapshot.MapMarkerLastRightClickTileY = mapMarkerDiagnostics.LastRightClickTileY;
            snapshot.MapMarkerLastRightClickTransformSource = mapMarkerDiagnostics.LastRightClickTransformSource;
            snapshot.MapMarkerLastRightClickFallbackReason = mapMarkerDiagnostics.LastRightClickFallbackReason;
            snapshot.MapMarkerLastRightClickMapFullscreenPosX = mapMarkerDiagnostics.LastRightClickMapFullscreenPosX;
            snapshot.MapMarkerLastRightClickMapFullscreenPosY = mapMarkerDiagnostics.LastRightClickMapFullscreenPosY;
            snapshot.MapMarkerLastRightClickMapScale = mapMarkerDiagnostics.LastRightClickMapScale;
            snapshot.MapMarkerLastRightClickTransformAgeUpdates = mapMarkerDiagnostics.LastRightClickTransformAgeUpdates;
            snapshot.PlayerWorldMapMarkersUiOnlyActionCount = mapMarkerDiagnostics.UiOnlyActionCount;
            snapshot.MapMarkerPickerOpen = mapMarkerDiagnostics.PickerOpen;
            snapshot.MapMarkerPickerAnchorScreenX = mapMarkerDiagnostics.PickerAnchorScreenX;
            snapshot.MapMarkerPickerAnchorScreenY = mapMarkerDiagnostics.PickerAnchorScreenY;
            snapshot.MapMarkerPickerPanelX = mapMarkerDiagnostics.PickerPanelX;
            snapshot.MapMarkerPickerPanelY = mapMarkerDiagnostics.PickerPanelY;
            snapshot.MapMarkerPickerPanelClamped = mapMarkerDiagnostics.PickerPanelClamped;
            snapshot.MapMarkerPickerLastDraw = mapMarkerDiagnostics.PickerLastDraw;
            snapshot.MapMarkerPickerLastFullscreenDraw = mapMarkerDiagnostics.PickerLastFullscreenDraw;
            snapshot.MapMarkerPickerDrawRoute = mapMarkerDiagnostics.PickerDrawRoute;
            snapshot.MapMarkerPickerDrawSkippedReason = mapMarkerDiagnostics.PickerDrawSkippedReason;
            snapshot.MapMarkerPickerLastClick = mapMarkerDiagnostics.PickerLastClick;
            snapshot.MapMarkerPickerLastCloseReason = mapMarkerDiagnostics.PickerLastCloseReason;
            snapshot.PlayerWorldMapMarkersLastReadUtc = mapMarkerDiagnostics.LastReadUtc;
            snapshot.PlayerWorldMapMarkersLastWriteUtc = mapMarkerDiagnostics.LastWriteUtc;
            snapshot.DiagnosticsOverlayVisible = DiagnosticsOverlay.Visible;
            snapshot.DrawCallCount = DiagnosticsOverlay.DrawCallCount;
            snapshot.LastDrawUtc = DiagnosticsOverlay.LastDrawUtc;
            snapshot.LastUpdateUtc = RuntimeDiagnostics.LastUpdateUtc;
            snapshot.LastHeartbeatUtc = State == null ? null : State.LastHeartbeatUtc;
            snapshot.FeatureCount = featureInfo.TotalFeatures;
            snapshot.EnabledFeatureCount = featureInfo.EnabledFeatures;
            snapshot.AppSettingsEnabledFeatureCount = ConfigService.CountAppSettingsEnabledFeatures();
            snapshot.FeatureSettingsEnabledFeatureCount = ConfigService.CountFeatureSettingsEnabledFeatures();
            snapshot.EffectiveEnabledFeatureCount = ConfigService.CountEffectiveEnabledFeatures();
            snapshot.FeatureCatalogCount = _featureCatalogCount;
            snapshot.ImplementedFeatureCount = _implementedFeatureCount;
            snapshot.VisibleFeatureCount = _visibleFeatureCount;
            snapshot.HotkeyVisibleFeatureCount = _hotkeyVisibleFeatureCount;
            snapshot.UserCategoryCounts = _userCategoryCounts;
            snapshot.CodeDomainCounts = _codeDomainCounts;
            snapshot.FeatureManagerUpdateCount = featureInfo.UpdateCount;
            snapshot.WorldGenDebugViewerConfiguredEnabled = ConfigService.AppSettings != null && ConfigService.AppSettings.DiagnosticsWorldGenDebugViewerEnabled;
            snapshot.DeveloperDebugCommandsConfiguredEnabled = ConfigService.AppSettings != null && ConfigService.AppSettings.DiagnosticsDeveloperDebugCommandsEnabled;
            snapshot.WorldGenDebugViewerSessionConfiguredEnabled = WorldGenDebugCompat.WorldGenSessionConfiguredEnabled;
            snapshot.DeveloperDebugCommandsSessionConfiguredEnabled = WorldGenDebugCompat.SessionConfiguredEnabled;
            snapshot.WorldGenDebugAttempted = WorldGenDebugCompat.Attempted;
            snapshot.WorldGenDebugFieldEnabled = WorldGenDebugCompat.Enabled;
            snapshot.WorldGenDebugStatus = WorldGenDebugCompat.Status;
            snapshot.WorldGenDebugMessage = WorldGenDebugCompat.Message;
            snapshot.WorldGenDebugFieldOwner = WorldGenDebugCompat.FieldOwner;
            snapshot.WorldGenDebugLastAttemptUtc = WorldGenDebugCompat.LastAttemptUtc;
            snapshot.IsInMainMenu = gameState.IsInMainMenu;
            snapshot.IsInWorld = gameState.IsInWorld;
            snapshot.GameInputAvailable = IsGameInputAvailable(gameState);
            snapshot.DiagnosticInputSkipped = RuntimeTargetingDiagnostics.DiagnosticInputSkipped;
            snapshot.DiagnosticInputGateStatus = RuntimeTargetingDiagnostics.DiagnosticInputGateStatus;
            snapshot.DiagnosticInputSkipReason = RuntimeTargetingDiagnostics.DiagnosticInputSkipReason;
            snapshot.DiagnosticInputSkipUtc = RuntimeTargetingDiagnostics.DiagnosticInputSkipUtc;
            snapshot.PlayerLife = gameState.Player == null ? 0 : gameState.Player.Life;
            snapshot.PlayerLifeMax = gameState.Player == null ? 0 : gameState.Player.LifeMax;
            snapshot.PlayerMana = gameState.Player == null ? 0 : gameState.Player.Mana;
            snapshot.PlayerManaMax = gameState.Player == null ? 0 : gameState.Player.ManaMax;
            snapshot.SelectedItemType = gameState.Inventory == null || gameState.Inventory.SelectedItem == null ? 0 : gameState.Inventory.SelectedItem.Type;
            snapshot.SelectedItemName = gameState.Inventory == null || gameState.Inventory.SelectedItem == null ? string.Empty : gameState.Inventory.SelectedItem.Name;
            snapshot.InventoryNonEmptyCount = gameState.Inventory == null ? 0 : gameState.Inventory.NonEmptyCount;
            snapshot.ActiveBuffCount = gameState.ActiveBuffs == null ? 0 : gameState.ActiveBuffs.Count;
            snapshot.ActiveNpcCount = gameState.Npcs == null ? 0 : gameState.Npcs.ActiveNpcCount;
            snapshot.TownNpcCount = gameState.Npcs == null ? 0 : gameState.Npcs.TownNpcCount;
            snapshot.HostileNpcCount = gameState.Npcs == null ? 0 : gameState.Npcs.HostileNpcCount;
            snapshot.CritterCount = gameState.Npcs == null ? 0 : gameState.Npcs.CritterCount;
            snapshot.LastGameStateReadUtc = gameState.LastReadUtc;
            snapshot.LastGameStateReadError = gameState.LastReadError;
            snapshot.LastGameStateInventoryProfile = GameStateReader.LastInventoryProfile.ToString();
            snapshot.LastGameStateNpcProfile = GameStateReader.LastNpcProfile.ToString();
            snapshot.LastGameStateTileProfile = GameStateReader.LastTileProfile.ToString();
        }
    }
}
