using System;
using JueMingZ.Actions;
using JueMingZ.Automation.AutoRecovery;
using JueMingZ.Automation.Combat;
using JueMingZ.Automation.Fishing;
using JueMingZ.Automation.Information;
using JueMingZ.Automation.InventoryAndItems;
using JueMingZ.Automation.Movement;
using JueMingZ.Automation.NpcServices;
using JueMingZ.Automation.Search.ChestLocator;
using JueMingZ.Automation.WorldAutomation;
using JueMingZ.Bootstrap;
using JueMingZ.Common;
using JueMingZ.Compat;
using JueMingZ.Config;
using JueMingZ.Diagnostics;
using JueMingZ.Features;
using JueMingZ.GameState;
using JueMingZ.Input;
using JueMingZ.UI;
using JueMingZ.UI.Information;
using JueMingZ.UI.Legacy;

namespace JueMingZ.Runtime
{
    internal static partial class RuntimeDiagnosticSnapshotBuilder
    {
        private static void WriteInventoryInformationFishing(DiagnosticSnapshot snapshot, RuntimeDiagnosticSnapshotSource source)
        {
            var settingsSnapshot = source.SettingsSnapshot;
            var fishingHasResidualState = source.FishingHasResidualState;
            var autoStack = AutoStackService.GetDiagnostics();
            var autoSell = AutoSellService.GetDiagnostics();
            var autoDiscard = AutoDiscardService.GetDiagnostics();
            var quickReforge = QuickReforgeService.GetDiagnostics();
            var autoCaptureCritter = AutoCaptureCritterService.GetDiagnostics();
            var autoHarvest = AutoHarvestService.GetDiagnostics();
            var quickBagOpen = QuickBagOpenService.GetDiagnostics();
            var autoDepositCoins = AutoDepositCoinsService.GetDiagnostics();
            var autoExtractinator = AutoExtractinatorService.GetDiagnostics();
            var keepFavorited = KeepFavoritedService.GetDiagnostics();
            var autoTaxCollect = AutoTaxCollectorService.GetDiagnostics();
            var information = InformationOverlayService.GetDiagnostics();
            var chestLocatorOverlay = ChestItemLocatorOverlayService.GetDiagnostics();
            var chestLocatorSectionRequest = ChestItemLocatorSectionRequestService.GetDiagnostics();
            var quickAnnouncement = MapQuickAnnouncementDiagnostics.GetSnapshot();
            var fishing = FishingAutomationService.GetDiagnostics();

            snapshot.AutoStackLastDecision = autoStack == null ? string.Empty : autoStack.LastDecision;
            snapshot.AutoStackLastInventorySignature = autoStack == null ? string.Empty : autoStack.LastInventorySignature;
            snapshot.AutoStackLastPendingItemIds = autoStack == null ? string.Empty : autoStack.LastPendingItemIds;
            snapshot.AutoStackLastDetectedItemIds = autoStack == null ? string.Empty : autoStack.LastDetectedItemIds;
            snapshot.AutoStackPendingSinceTick = autoStack == null ? 0 : autoStack.PendingSinceTick;
            snapshot.AutoStackLastPendingChangeTick = autoStack == null ? -1 : autoStack.LastPendingChangeTick;
            snapshot.AutoStackLastPendingClearReason = autoStack == null ? string.Empty : autoStack.LastPendingClearReason;
            snapshot.AutoStackPendingTransactionState = autoStack == null ? string.Empty : autoStack.PendingTransactionState;
            snapshot.AutoStackPendingRetryCount = autoStack == null ? 0 : autoStack.PendingRetryCount;
            snapshot.AutoStackLastSubmitRequestId = autoStack == null ? string.Empty : autoStack.LastSubmitRequestId;
            snapshot.AutoStackLastResult = autoStack == null ? string.Empty : autoStack.LastResult;
            snapshot.AutoStackLastUnverifiedReason = autoStack == null ? string.Empty : autoStack.LastUnverifiedReason;
            snapshot.AutoStackInventoryTransactionSlots = autoStack == null ? string.Empty : autoStack.InventoryTransactionSlots;
            snapshot.AutoStackInventoryTransactionBlockingReason = autoStack == null ? string.Empty : autoStack.InventoryTransactionBlockingReason;
            snapshot.AutoStackActionResultDeliveryMode = autoStack == null ? string.Empty : autoStack.ActionResultDeliveryMode;
            snapshot.AutoStackLastDecisionUtc = autoStack == null ? null : autoStack.LastDecisionUtc;
            snapshot.AutoSellLastDecision = autoSell == null ? string.Empty : autoSell.LastDecision;
            snapshot.AutoSellLastInventorySignature = autoSell == null ? string.Empty : autoSell.LastInventorySignature;
            snapshot.AutoSellLastItemIds = autoSell == null ? string.Empty : autoSell.LastSellItemIds;
            snapshot.AutoSellLastDecisionUtc = autoSell == null ? null : autoSell.LastDecisionUtc;
            snapshot.AutoDiscardLastDecision = autoDiscard == null ? string.Empty : autoDiscard.LastDecision;
            snapshot.AutoDiscardLastInventorySignature = autoDiscard == null ? string.Empty : autoDiscard.LastInventorySignature;
            snapshot.AutoDiscardLastItemIds = autoDiscard == null ? string.Empty : autoDiscard.LastDiscardItemIds;
            snapshot.AutoDiscardLastDecisionUtc = autoDiscard == null ? null : autoDiscard.LastDecisionUtc;
            snapshot.QuickReforgeLastDecision = quickReforge == null ? string.Empty : quickReforge.LastDecision;
            snapshot.QuickReforgeLastTargetPrefixes = quickReforge == null ? string.Empty : quickReforge.LastTargetPrefixes;
            snapshot.QuickReforgeLastMatchedPrefix = quickReforge == null ? string.Empty : quickReforge.LastMatchedPrefix;
            snapshot.QuickReforgeLastDecisionUtc = quickReforge == null ? null : quickReforge.LastDecisionUtc;
            snapshot.AutoTaxCollectLastDecision = autoTaxCollect == null ? string.Empty : autoTaxCollect.LastDecision;
            snapshot.AutoTaxCollectLastDecisionUtc = autoTaxCollect == null ? null : autoTaxCollect.LastDecisionUtc;
            snapshot.AutoTaxCollectTargetNpcIndex = autoTaxCollect == null ? -1 : autoTaxCollect.LastTargetNpcIndex;
            snapshot.AutoTaxCollectTargetWhoAmI = autoTaxCollect == null ? -1 : autoTaxCollect.LastTargetWhoAmI;
            snapshot.AutoTaxCollectTargetName = autoTaxCollect == null ? string.Empty : autoTaxCollect.LastTargetName;
            snapshot.AutoTaxCollectTaxMoney = autoTaxCollect == null ? 0 : autoTaxCollect.LastTaxMoney;
            snapshot.AutoTaxCollectLastRequestId = autoTaxCollect == null ? string.Empty : autoTaxCollect.LastRequestId;
            snapshot.AutoCaptureCritterLastDecision = autoCaptureCritter == null ? string.Empty : autoCaptureCritter.LastDecision;
            snapshot.AutoCaptureCritterLastDecisionUtc = autoCaptureCritter == null ? null : autoCaptureCritter.LastDecisionUtc;
            snapshot.AutoCaptureCritterBugNetSlot = autoCaptureCritter == null ? -1 : autoCaptureCritter.BugNetSlot;
            snapshot.AutoCaptureCritterBugNetItemType = autoCaptureCritter == null ? 0 : autoCaptureCritter.BugNetItemType;
            snapshot.AutoCaptureCritterTargetNpcIndex = autoCaptureCritter == null ? -1 : autoCaptureCritter.TargetNpcIndex;
            snapshot.AutoCaptureCritterTargetNpcType = autoCaptureCritter == null ? 0 : autoCaptureCritter.TargetNpcType;
            snapshot.AutoCaptureCritterFishingProtectionState = autoCaptureCritter == null ? string.Empty : autoCaptureCritter.FishingProtectionState;
            snapshot.AutoHarvestLastDecision = autoHarvest == null ? string.Empty : autoHarvest.LastDecision;
            snapshot.AutoHarvestLastDecisionUtc = autoHarvest == null ? null : autoHarvest.LastDecisionUtc;
            snapshot.AutoHarvestLastAction = autoHarvest == null ? string.Empty : autoHarvest.LastAction;
            snapshot.AutoHarvestToolSlot = autoHarvest == null ? -1 : autoHarvest.ToolSlot;
            snapshot.AutoHarvestToolItemType = autoHarvest == null ? 0 : autoHarvest.ToolItemType;
            snapshot.AutoHarvestTargetTileX = autoHarvest == null ? -1 : autoHarvest.TargetTileX;
            snapshot.AutoHarvestTargetTileY = autoHarvest == null ? -1 : autoHarvest.TargetTileY;
            snapshot.AutoHarvestTargetSeedItemType = autoHarvest == null ? 0 : autoHarvest.TargetSeedItemType;
            snapshot.AutoHarvestPendingReplantCount = autoHarvest == null ? 0 : autoHarvest.PendingReplantCount;
            snapshot.QuickBagOpenLastDecision = quickBagOpen == null ? string.Empty : quickBagOpen.LastDecision;
            snapshot.QuickBagOpenLastDecisionUtc = quickBagOpen == null ? null : quickBagOpen.LastDecisionUtc;
            snapshot.QuickBagOpenBagSlot = quickBagOpen == null ? -1 : quickBagOpen.BagSlot;
            snapshot.QuickBagOpenBagItemType = quickBagOpen == null ? 0 : quickBagOpen.BagItemType;
            snapshot.QuickBagOpenBagItemName = quickBagOpen == null ? string.Empty : quickBagOpen.BagItemName;
            snapshot.AutoDepositCoinsLastDecision = autoDepositCoins == null ? string.Empty : autoDepositCoins.LastDecision;
            snapshot.AutoDepositCoinsLastDecisionUtc = autoDepositCoins == null ? null : autoDepositCoins.LastDecisionUtc;
            snapshot.AutoDepositCoinsLastInventorySignature = autoDepositCoins == null ? string.Empty : autoDepositCoins.LastInventorySignature;
            snapshot.AutoDepositCoinsLastCoinItemIds = autoDepositCoins == null ? string.Empty : autoDepositCoins.LastCoinItemIds;
            snapshot.AutoExtractinatorLastDecision = autoExtractinator == null ? string.Empty : autoExtractinator.LastDecision;
            snapshot.AutoExtractinatorLastDecisionUtc = autoExtractinator == null ? null : autoExtractinator.LastDecisionUtc;
            snapshot.AutoExtractinatorItemSlot = autoExtractinator == null ? -1 : autoExtractinator.ItemSlot;
            snapshot.AutoExtractinatorItemType = autoExtractinator == null ? 0 : autoExtractinator.ItemType;
            snapshot.AutoExtractinatorTileX = autoExtractinator == null ? -1 : autoExtractinator.ExtractinatorTileX;
            snapshot.AutoExtractinatorTileY = autoExtractinator == null ? -1 : autoExtractinator.ExtractinatorTileY;
            snapshot.AutoExtractinatorTileType = autoExtractinator == null ? 0 : autoExtractinator.ExtractinatorTileType;
            snapshot.KeepFavoritedLastDecision = keepFavorited == null ? string.Empty : keepFavorited.LastDecision;
            snapshot.KeepFavoritedLastDecisionUtc = keepFavorited == null ? null : keepFavorited.LastDecisionUtc;
            snapshot.KeepFavoritedSlot = keepFavorited == null ? -1 : keepFavorited.Slot;
            snapshot.KeepFavoritedItemType = keepFavorited == null ? 0 : keepFavorited.ItemType;
            snapshot.KeepFavoritedSignature = keepFavorited == null ? string.Empty : keepFavorited.Signature;
            snapshot.InformationEnabledSummary = information == null ? string.Empty : information.EnabledSummary;
            snapshot.InformationNpcLabelsDrawn = information == null ? 0 : information.NpcLabelsDrawn;
            snapshot.InformationChestLabelsDrawn = information == null ? 0 : information.ChestLabelsDrawn;
            snapshot.InformationSignTextLabelsDrawn = information == null ? 0 : information.SignTextLabelsDrawn;
            snapshot.InformationTombstoneTextLabelsDrawn = information == null ? 0 : information.TombstoneTextLabelsDrawn;
            snapshot.InformationTileHighlightsDrawn = information == null ? 0 : information.TileHighlightsDrawn;
            snapshot.InformationStatusLinesDrawn = information == null ? 0 : information.StatusLinesDrawn;
            snapshot.InformationLastDrawElapsedMs = information == null ? 0d : information.LastDrawElapsedMs;
            snapshot.InformationLastSkipReason = information == null ? string.Empty : information.LastSkipReason;
            snapshot.InformationStatusPanelLayoutCacheHitCount = InformationStatusPanelService.LayoutCacheHitCount;
            snapshot.InformationStatusPanelLayoutCacheMissCount = InformationStatusPanelService.LayoutCacheMissCount;
            snapshot.InformationSignTextLayoutCacheHitCount = information == null ? 0 : information.SignTextLayoutCacheHitCount;
            snapshot.InformationSignTextLayoutCacheMissCount = information == null ? 0 : information.SignTextLayoutCacheMissCount;
            snapshot.InformationWorldLabelSnapshotRefreshCount = information == null ? 0 : information.WorldLabelSnapshotRefreshCount;
            snapshot.InformationNpcLabelSnapshotRefreshCount = information == null ? 0 : information.NpcLabelSnapshotRefreshCount;
            snapshot.InformationChestLabelSnapshotRefreshCount = information == null ? 0 : information.ChestLabelSnapshotRefreshCount;
            snapshot.InformationChestLabelSortRefreshCount = information == null ? 0 : information.ChestLabelSortRefreshCount;
            snapshot.InformationChestAlwaysScanCacheHitCount = information == null ? 0 : information.ChestAlwaysScanCacheHitCount;
            snapshot.InformationChestAlwaysScanCacheMissCount = information == null ? 0 : information.ChestAlwaysScanCacheMissCount;
            snapshot.InformationChestAlwaysLastDirtyReason = information == null ? string.Empty : information.ChestAlwaysLastDirtyReason;
            snapshot.InformationChestAlwaysSafeRefreshCount = information == null ? 0 : information.ChestAlwaysSafeRefreshCount;
            snapshot.InformationChestAlwaysTilesVisitedLast = information == null ? 0 : information.ChestAlwaysTilesVisitedLast;
            snapshot.InformationChestAlwaysTypedTileFastPathStatus = information == null ? string.Empty : information.ChestAlwaysTypedTileFastPathStatus;
            snapshot.InformationChestAlwaysNameCacheHitCount = information == null ? 0 : information.ChestAlwaysNameCacheHitCount;
            snapshot.InformationChestAlwaysNameCacheMissCount = information == null ? 0 : information.ChestAlwaysNameCacheMissCount;
            snapshot.InformationChestAlwaysPartialScanFrameCount = information == null ? 0 : information.ChestAlwaysPartialScanFrameCount;
            snapshot.InformationChestAlwaysPartialScanPendingCount = information == null ? 0 : information.ChestAlwaysPartialScanPendingCount;
            snapshot.InformationChestAlwaysStableSnapshotId = information == null ? 0 : information.ChestAlwaysStableSnapshotId;
            snapshot.InformationWorldContextCacheHitCount = information == null ? 0 : information.WorldContextCacheHitCount;
            snapshot.InformationWorldContextCacheMissCount = information == null ? 0 : information.WorldContextCacheMissCount;
            snapshot.InformationWorldContextProfile = information == null ? string.Empty : information.WorldContextProfile;
            snapshot.InformationWorldContextFileDataRefreshCount = information == null ? 0 : information.WorldContextFileDataRefreshCount;
            snapshot.InformationStatusLineCacheHitCount = information == null ? 0 : information.StatusLineCacheHitCount;
            snapshot.InformationStatusLineCacheMissCount = information == null ? 0 : information.StatusLineCacheMissCount;
            snapshot.InformationFishingCatchEarlyCacheHitCount = information == null ? 0 : information.FishingCatchEarlyCacheHitCount;
            snapshot.InformationFishingCatchEarlyCacheMissCount = information == null ? 0 : information.FishingCatchEarlyCacheMissCount;
            snapshot.InformationFishingWaterScanCount = information == null ? 0 : information.FishingWaterScanCount;
            snapshot.InformationFishingConditionsReadCount = information == null ? 0 : information.FishingConditionsReadCount;
            snapshot.InformationFishingBobberObserverFreshInactiveSkipCount = information == null ? 0 : information.FishingBobberObserverFreshInactiveSkipCount;
            snapshot.InformationFishingProjectileFallbackScanCount = information == null ? 0 : information.FishingProjectileFallbackScanCount;
            snapshot.SearchChestLocatorOverlayEnabled = chestLocatorOverlay != null && chestLocatorOverlay.Enabled;
            snapshot.SearchChestLocatorOverlayQueryVersion = chestLocatorOverlay == null ? 0 : chestLocatorOverlay.QueryVersion;
            snapshot.SearchChestLocatorOverlaySnapshotStatus = chestLocatorOverlay == null ? string.Empty : chestLocatorOverlay.SnapshotStatus;
            snapshot.SearchChestLocatorOverlayCandidateChestCount = chestLocatorOverlay == null ? 0 : chestLocatorOverlay.CandidateChestCount;
            snapshot.SearchChestLocatorOverlayScannedChestCount = chestLocatorOverlay == null ? 0 : chestLocatorOverlay.ScannedChestCount;
            snapshot.SearchChestLocatorOverlayHitCount = chestLocatorOverlay == null ? 0 : chestLocatorOverlay.HitCount;
            snapshot.SearchChestLocatorOverlayDrawnHitCount = chestLocatorOverlay == null ? 0 : chestLocatorOverlay.DrawnHitCount;
            snapshot.SearchChestLocatorOverlaySkipReason = chestLocatorOverlay == null ? string.Empty : chestLocatorOverlay.SkipReason;
            snapshot.SearchChestLocatorOverlayRecentElapsedBucket = chestLocatorOverlay == null ? string.Empty : chestLocatorOverlay.RecentElapsedBucket;
            snapshot.SearchChestLocatorOverlaySnapshotAgeTicks = chestLocatorOverlay == null ? 0 : chestLocatorOverlay.SnapshotAgeTicks;
            snapshot.SearchChestLocatorSectionRequestEnabled = chestLocatorSectionRequest != null && chestLocatorSectionRequest.Enabled;
            snapshot.SearchChestLocatorSectionRequestMultiplayerClient = chestLocatorSectionRequest != null && chestLocatorSectionRequest.MultiplayerClient;
            snapshot.SearchChestLocatorSectionRequestAttempted = chestLocatorSectionRequest != null && chestLocatorSectionRequest.Attempted;
            snapshot.SearchChestLocatorSectionRequestSent = chestLocatorSectionRequest != null && chestLocatorSectionRequest.Sent;
            snapshot.SearchChestLocatorSectionRequestThrottled = chestLocatorSectionRequest != null && chestLocatorSectionRequest.Throttled;
            snapshot.SearchChestLocatorSectionRequestStatus = chestLocatorSectionRequest == null ? string.Empty : chestLocatorSectionRequest.Status;
            snapshot.SearchChestLocatorSectionRequestFailureReason = chestLocatorSectionRequest == null ? string.Empty : chestLocatorSectionRequest.FailureReason;
            snapshot.SearchChestLocatorSectionRequestSectionKey = chestLocatorSectionRequest == null ? string.Empty : chestLocatorSectionRequest.SectionKey;
            snapshot.SearchChestLocatorSectionRequestSectionX = chestLocatorSectionRequest == null ? -1 : chestLocatorSectionRequest.SectionX;
            snapshot.SearchChestLocatorSectionRequestSectionY = chestLocatorSectionRequest == null ? -1 : chestLocatorSectionRequest.SectionY;
            snapshot.SearchChestLocatorSectionRequestQueryVersion = chestLocatorSectionRequest == null ? 0 : chestLocatorSectionRequest.QueryVersion;
            snapshot.SearchChestLocatorSectionRequestTick = chestLocatorSectionRequest == null ? 0 : (long)Math.Min((ulong)long.MaxValue, chestLocatorSectionRequest.RequestTick);
            snapshot.SearchChestLocatorSectionRequestCooldownRemainingTicks = chestLocatorSectionRequest == null ? 0 : (long)Math.Min((ulong)long.MaxValue, chestLocatorSectionRequest.CooldownRemainingTicks);
            snapshot.MapQuickAnnouncementLastTriggered = quickAnnouncement.LastTriggered;
            snapshot.MapQuickAnnouncementLastResultCode = quickAnnouncement.LastResultCode;
            snapshot.MapQuickAnnouncementLastTargetKind = quickAnnouncement.LastTargetKind;
            snapshot.MapQuickAnnouncementLastTargetName = quickAnnouncement.LastTargetName;
            snapshot.MapQuickAnnouncementLastTargetSummary = quickAnnouncement.LastTargetSummary;
            snapshot.MapQuickAnnouncementLastTargetCount = quickAnnouncement.LastTargetCount;
            snapshot.MapQuickAnnouncementLastResolveDetail = quickAnnouncement.LastResolveDetail;
            snapshot.MapQuickAnnouncementLastTargetSource = quickAnnouncement.LastTargetSource;
            snapshot.MapQuickAnnouncementLastUiHoverSource = quickAnnouncement.LastUiHoverSource;
            snapshot.MapQuickAnnouncementLastUiHoverState = quickAnnouncement.LastUiHoverState;
            snapshot.MapQuickAnnouncementLastUiHoverHookStatus = quickAnnouncement.LastUiHoverHookStatus;
            snapshot.MapQuickAnnouncementLastPendingState = quickAnnouncement.LastPendingState;
            snapshot.MapQuickAnnouncementLastHoverCacheAgeUpdates = quickAnnouncement.LastHoverCacheAgeUpdates;
            snapshot.MapQuickAnnouncementLastPlacementLookupSource = quickAnnouncement.LastPlacementLookupSource;
            snapshot.MapQuickAnnouncementLastFallbackReason = quickAnnouncement.LastFallbackReason;
            snapshot.MapQuickAnnouncementLastIsAir = quickAnnouncement.LastIsAir;
            snapshot.MapQuickAnnouncementLastCooldownBlocked = quickAnnouncement.LastCooldownBlocked;
            snapshot.MapQuickAnnouncementLastSendSucceeded = quickAnnouncement.LastSendSucceeded;
            snapshot.MapQuickAnnouncementLastFailureReason = quickAnnouncement.LastFailureReason;
            snapshot.MapQuickAnnouncementLastHotkeySummary = quickAnnouncement.LastHotkeySummary;
            snapshot.MapQuickAnnouncementLastInputConsumed = quickAnnouncement.LastInputConsumed;
            snapshot.MapQuickAnnouncementLastInputConsumeResult = quickAnnouncement.LastInputConsumeResult;
            snapshot.MapQuickAnnouncementLastVisibilityVerdict = quickAnnouncement.LastVisibilityVerdict;
            snapshot.MapQuickAnnouncementLastVisibilityReason = quickAnnouncement.LastVisibilityReason;
            snapshot.MapQuickAnnouncementLastVisibleLayers = quickAnnouncement.LastVisibleLayers;
            snapshot.MapQuickAnnouncementLastBlockedLayers = quickAnnouncement.LastBlockedLayers;
            snapshot.MapQuickAnnouncementLastCircuitOnly = quickAnnouncement.LastCircuitOnly;
            snapshot.MapQuickAnnouncementLastEchoGate = quickAnnouncement.LastEchoGate;
            snapshot.MapQuickAnnouncementLastInvisibleAir = quickAnnouncement.LastInvisibleAir;
            snapshot.MapQuickAnnouncementLastVisibilityUnavailableReason = quickAnnouncement.LastVisibilityUnavailableReason;
            snapshot.MapQuickAnnouncementLastDecisionUtc = quickAnnouncement.LastDecisionUtc;
            snapshot.FishingAutomationNeedsTick = settingsSnapshot.FishingAutomationNeedsTick;
            snapshot.FishingDisplayNeedsCatchResolver = settingsSnapshot.FishingDisplayNeedsCatchResolver;
            snapshot.FishingHasResidualState = fishingHasResidualState;
            snapshot.FishingSessionActive = fishing != null && fishing.FishingSessionActive;
            snapshot.FishingLastDecision = fishing == null ? string.Empty : fishing.FishingLastDecision;
            snapshot.FishingLastSkipReason = fishing == null ? string.Empty : fishing.FishingLastSkipReason;
            snapshot.FishingCurrentBobberIdentity = fishing == null ? -1 : fishing.FishingCurrentBobberIdentity;
            snapshot.FishingLastProcessedHookIdentity = fishing == null ? -1 : fishing.FishingLastProcessedHookIdentity;
            snapshot.FishingWaitingForBobberGone = fishing != null && fishing.FishingWaitingForBobberGone;
            snapshot.FishingRecastDelayTicks = fishing == null ? 0 : fishing.FishingRecastDelayTicks;
            snapshot.FishingRecastWaitingForBobber = fishing != null && fishing.FishingRecastWaitingForBobber;
            snapshot.FishingRecastBobberWaitTicks = fishing == null ? 0 : fishing.FishingRecastBobberWaitTicks;
            snapshot.FishingRecastRetryCount = fishing == null ? 0 : fishing.FishingRecastRetryCount;
            snapshot.FishingFilterSkipInProgress = fishing != null && fishing.FishingFilterSkipInProgress;
            snapshot.FishingFilterSkipRequestId = fishing == null ? string.Empty : fishing.FishingFilterSkipRequestId;
            snapshot.FishingFilterSkipWaitingForBobberGone = fishing != null && fishing.FishingFilterSkipWaitingForBobberGone;
            snapshot.FishingFilterSkipTemporarySlot = fishing == null ? -1 : fishing.FishingFilterSkipTemporarySlot;
            snapshot.FishingFilterSkipLastResult = fishing == null ? string.Empty : fishing.FishingFilterSkipLastResult;
            snapshot.FishingFilterSkipRestoreFailureReason = fishing == null ? string.Empty : fishing.FishingFilterSkipRestoreFailureReason;
            snapshot.FishingCastWorldX = fishing == null ? 0f : fishing.FishingCastWorldX;
            snapshot.FishingCastWorldY = fishing == null ? 0f : fishing.FishingCastWorldY;
            snapshot.FishingOriginalLoadoutIndex = fishing == null ? -1 : fishing.FishingOriginalLoadoutIndex;
            snapshot.FishingTargetLoadoutIndex = fishing == null ? -1 : fishing.FishingTargetLoadoutIndex;
            snapshot.FishingAutoEquipmentApplied = fishing != null && fishing.FishingAutoEquipmentApplied;
            snapshot.FishingAutoEquipmentPendingRestoreCount = fishing == null ? 0 : fishing.FishingAutoEquipmentPendingRestoreCount;
            snapshot.FishingAutoEquipmentLastDecision = fishing == null ? string.Empty : fishing.FishingAutoEquipmentLastDecision;
            snapshot.FishingAutoEquipmentLastSkipReason = fishing == null ? string.Empty : fishing.FishingAutoEquipmentLastSkipReason;
            snapshot.FishingAutoEquipmentAppliedMoveCount = fishing == null ? 0 : fishing.FishingAutoEquipmentAppliedMoveCount;
            snapshot.FishingAutoEquipmentStillHoldingOriginalRod = fishing != null && fishing.FishingAutoEquipmentStillHoldingOriginalRod;
            snapshot.FishingAutoEquipmentManualInventoryInteractionDetected = fishing != null && fishing.FishingAutoEquipmentManualInventoryInteractionDetected;
            snapshot.FishingQuestFishStoreCooldownTicks = fishing == null ? 0 : fishing.FishingQuestFishStoreCooldownTicks;
            snapshot.FishingQuestFishLastItemId = fishing == null ? 0 : fishing.FishingQuestFishLastItemId;
            snapshot.FishingQuestFishLastSlotCount = fishing == null ? 0 : fishing.FishingQuestFishLastSlotCount;
            snapshot.FishingAutoStoreLastMode = fishing == null ? string.Empty : fishing.FishingAutoStoreLastMode;
            snapshot.FishingAutoStoreLastInventorySignature = fishing == null ? string.Empty : fishing.FishingAutoStoreLastInventorySignature;
            snapshot.FishingAutoStoreLastPendingItemIds = fishing == null ? string.Empty : fishing.FishingAutoStoreLastPendingItemIds;
            snapshot.FishingAutoStoreLastDiagnosticMessage = fishing == null ? string.Empty : fishing.FishingAutoStoreLastDiagnosticMessage;
            snapshot.FishingHookInstalled = fishing != null && fishing.FishingHookInstalled;
            snapshot.FishingHookLastObservationTick = fishing == null ? 0 : fishing.FishingHookLastObservationTick;
            snapshot.FishingFallbackScanExecutedCount = fishing == null ? 0 : fishing.FishingFallbackScanExecutedCount;
            snapshot.FishingFallbackScanSkippedHookFreshCount = fishing == null ? 0 : fishing.FishingFallbackScanSkippedHookFreshCount;
            snapshot.FishingFallbackScanForcedDisappearanceConfirmationCount = fishing == null ? 0 : fishing.FishingFallbackScanForcedDisappearanceConfirmationCount;
            snapshot.FishingAutomationDispatchReason = fishing == null ? string.Empty : fishing.FishingAutomationDispatchReason;
            snapshot.FishingAutomationDispatchCadenceTicks = fishing == null ? 0 : fishing.FishingAutomationDispatchCadenceTicks;
            snapshot.FishingAutomationIdleFastSkipCount = fishing == null ? 0 : fishing.FishingAutomationIdleFastSkipCount;
            snapshot.FishingAutomationIdleWatchdogTickCount = fishing == null ? 0 : fishing.FishingAutomationIdleWatchdogTickCount;
            snapshot.FishingObserverFreshActiveCount = fishing == null ? 0 : fishing.FishingObserverFreshActiveCount;
            snapshot.FishingObserverFreshInactiveSkipCount = fishing == null ? 0 : fishing.FishingObserverFreshInactiveSkipCount;
            snapshot.FishingFallbackScanIdleSkippedCount = fishing == null ? 0 : fishing.FishingFallbackScanIdleSkippedCount;
            snapshot.FishingFallbackScanHookStaleCount = fishing == null ? 0 : fishing.FishingFallbackScanHookStaleCount;
            snapshot.FishingTickSubpathLast = fishing == null ? string.Empty : fishing.FishingTickSubpathLast;
            snapshot.FishingResidualStateMask = fishing == null ? 0 : fishing.FishingResidualStateMask;
            snapshot.FishingFilterMode = fishing == null || string.IsNullOrWhiteSpace(fishing.FishingFilterMode) ? settingsSnapshot.FishingFilterMode : fishing.FishingFilterMode;
            snapshot.FishingFilterMatchMode = fishing == null || string.IsNullOrWhiteSpace(fishing.FishingFilterMatchMode) ? settingsSnapshot.FishingFilterMatchMode : fishing.FishingFilterMatchMode;
            snapshot.FishingFilterCatchKind = fishing == null ? string.Empty : fishing.FishingFilterCatchKind;
            snapshot.FishingFilterCatchId = fishing == null ? 0 : fishing.FishingFilterCatchId;
            snapshot.FishingFilterCatchName = fishing == null ? string.Empty : fishing.FishingFilterCatchName;
            snapshot.FishingFilterDecision = fishing == null ? string.Empty : fishing.FishingFilterDecision;
            snapshot.FishingFilterDecisionReason = fishing == null ? string.Empty : fishing.FishingFilterDecisionReason;
            snapshot.FishingFilterMatchedRule = fishing == null ? string.Empty : fishing.FishingFilterMatchedRule;
            snapshot.FishingFilterDryRun = fishing != null && fishing.FishingFilterDryRun;
            snapshot.FishingFilterCutRodSkipEnabled = settingsSnapshot.FishingFilterCutRodSkipEnabled;
        }
    }
}
