using System;
using JueMingZ.Actions;
using JueMingZ.Automation.AutoRecovery;
using JueMingZ.Automation.Combat;
using JueMingZ.Automation.Fishing;
using JueMingZ.Automation.Information;
using JueMingZ.Automation.InventoryAndItems;
using JueMingZ.Automation.MapEnhancement;
using JueMingZ.Automation.Movement;
using JueMingZ.Automation.NpcServices;
using JueMingZ.Automation.WorldAutomation;
using JueMingZ.Bootstrap;
using JueMingZ.Common;
using JueMingZ.Compat;
using JueMingZ.Config;
using JueMingZ.Diagnostics;
using JueMingZ.Features;
using JueMingZ.GameState;
using JueMingZ.Input;
using JueMingZ.Records;
using JueMingZ.UI;
using JueMingZ.UI.Information;
using JueMingZ.UI.Legacy;

namespace JueMingZ.Runtime
{
    internal static partial class RuntimeDiagnosticSnapshotBuilder
    {
        private static void WriteBootstrapAndGameState(DiagnosticSnapshot snapshot, RuntimeDiagnosticSnapshotSource source)
        {
            var _initialized = source.Context.Initialized;
            var Version = source.Context.Version;
            var TestRunId = source.Context.TestRunId;
            var State = source.Context.State;
            var _featureCatalogCount = source.Context.FeatureCatalogCount;
            var _implementedFeatureCount = source.Context.ImplementedFeatureCount;
            var _visibleFeatureCount = source.Context.VisibleFeatureCount;
            var _hotkeyVisibleFeatureCount = source.Context.HotkeyVisibleFeatureCount;
            var _userCategoryCounts = source.Context.UserCategoryCounts;
            var _codeDomainCounts = source.Context.CodeDomainCounts;
            var featureInfo = source.FeatureInfo;
            var gameState = source.GameState;
            var lateBootstrapCompleted = source.LateBootstrapCompleted;

            snapshot.Loaded = _initialized;
            snapshot.Version = Version;
            snapshot.RuntimeVersion = Version;
            snapshot.TestRunId = TestRunId;
            snapshot.ProcessName = GetProcessName();
            snapshot.BaseDirectory = AppDomain.CurrentDomain.BaseDirectory;
            snapshot.LogDirectory = Logger.LogDirectory;
            snapshot.TerrariaDetected = GameMode.IsTerrariaLoaded;
            snapshot.TerrariaVersion = lateBootstrapCompleted ? GameMode.GetTerrariaVersionLateOnly() : "EarlyUnavailable";
            snapshot.NetModeDescription = lateBootstrapCompleted ? GameMode.GetDescriptionLateOnly() : "EarlyUnavailable";
            snapshot.UpdateCount = State == null ? 0 : State.UpdateCount;
            snapshot.LateBootstrapCompleted = lateBootstrapCompleted;
            snapshot.SafeBootstrapStarted = AssemblyLoadTracker.SafeBootstrapStarted;
            snapshot.HarmonyLoaded = DependencyChecker.FindType("HarmonyLib.Harmony", "0Harmony") != null;
            snapshot.SafeBootstrapHookInstalled = HookDiagnostics.SafeBootstrapHookInstalled;
            snapshot.HookUpdateInstalled = HookDiagnostics.HookUpdateInstalled;
            snapshot.DrawHookInstalled = HookDiagnostics.DrawHookInstalled;
            snapshot.InterfaceLayerHookInstalled = HookDiagnostics.InterfaceLayerHookInstalled;
            snapshot.ItemCheckHookInstalled = HookDiagnostics.ItemCheckHookInstalled;
            snapshot.ItemCheckHookMethod = HookDiagnostics.ItemCheckHookMethod;
            snapshot.GoblinExecutionHookInstalled = HookDiagnostics.GoblinExecutionHookInstalled;
            snapshot.GoblinExecutionHookMethod = HookDiagnostics.GoblinExecutionHookMethod;
            snapshot.PlayerWorldDeathHookInstalled = HookDiagnostics.PlayerDeathHookInstalled;
            snapshot.PlayerWorldDeathHookMethod = HookDiagnostics.PlayerDeathHookMethod;
            snapshot.PlayerWorldDeathHookMessage = HookDiagnostics.PlayerDeathHookMessage;
            var deathDiagnostics = PlayerWorldDeathRecorder.LastDiagnostics;
            snapshot.PlayerWorldDeathLastRecordStatus = deathDiagnostics.LastRecordStatus;
            snapshot.PlayerWorldDeathLastRecordMessage = deathDiagnostics.LastRecordMessage;
            snapshot.PlayerWorldDeathLastEventId = deathDiagnostics.LastEventId;
            snapshot.PlayerWorldDeathLastPairId = deathDiagnostics.LastPairId;
            snapshot.PlayerWorldDeathLastDeathCount = deathDiagnostics.LastDeathCount;
            snapshot.PlayerWorldDeathHistoryReadFailed = deathDiagnostics.DeathHistoryReadFailed;
            var deathMarkerDiagnostics = PlayerWorldDeathMarkerDiagnostics.GetSnapshot();
            snapshot.PlayerWorldDeathMarkerLayerInstalled = deathMarkerDiagnostics.LayerInstalled;
            snapshot.PlayerWorldDeathMarkerLayerMessage = deathMarkerDiagnostics.LayerMessage;
            snapshot.PlayerWorldDeathMarkerLastStatus = deathMarkerDiagnostics.LastStatus;
            snapshot.PlayerWorldDeathMarkerLastMessage = deathMarkerDiagnostics.LastMessage;
            snapshot.PlayerWorldDeathMarkerLastPairId = deathMarkerDiagnostics.LastPairId;
            snapshot.PlayerWorldDeathMarkerCachedCount = deathMarkerDiagnostics.CachedCount;
            snapshot.PlayerWorldDeathMarkerDrawnCount = deathMarkerDiagnostics.DrawnCount;
            snapshot.PlayerWorldDeathMarkerCulledByLimit = deathMarkerDiagnostics.CulledByLimit;
            snapshot.PlayerWorldDeathMarkerHistoryReadFailed = deathMarkerDiagnostics.HistoryReadFailed;
            snapshot.PlayerWorldDeathMarkerLastDrawUtc = deathMarkerDiagnostics.LastDrawUtc;
            var deathHistoryDiagnostics = PlayerWorldDeathHistoryDiagnostics.GetSnapshot();
            snapshot.PlayerWorldDeathHistoryLastStatus = deathHistoryDiagnostics.LastStatus;
            snapshot.PlayerWorldDeathHistoryLastMessage = deathHistoryDiagnostics.LastMessage;
            snapshot.PlayerWorldDeathHistoryLastPairId = deathHistoryDiagnostics.LastPairId;
            snapshot.PlayerWorldDeathHistoryDeathCount = deathHistoryDiagnostics.DeathCount;
            snapshot.PlayerWorldDeathHistoryTotalEventCount = deathHistoryDiagnostics.TotalEventCount;
            snapshot.PlayerWorldDeathHistoryPageIndex = deathHistoryDiagnostics.PageIndex;
            snapshot.PlayerWorldDeathHistoryPageCount = deathHistoryDiagnostics.PageCount;
            snapshot.PlayerWorldDeathHistorySummaryReadFailed = deathHistoryDiagnostics.SummaryReadFailed;
            snapshot.PlayerWorldDeathHistoryPageReadFailed = deathHistoryDiagnostics.HistoryReadFailed;
            snapshot.PlayerWorldDeathHistoryLastReadUtc = deathHistoryDiagnostics.LastReadUtc;
            var playtimeDiagnostics = PlayerWorldPlaytimeDiagnostics.GetSnapshot();
            snapshot.PlayerWorldPlaytimeLastStatus = playtimeDiagnostics.LastStatus;
            snapshot.PlayerWorldPlaytimeLastMessage = playtimeDiagnostics.LastMessage;
            snapshot.PlayerWorldPlaytimeLastPairId = playtimeDiagnostics.LastPairId;
            snapshot.PlayerWorldPlaytimeTotalGameTicks = playtimeDiagnostics.TotalGameTicks;
            snapshot.PlayerWorldPlaytimeWholeDayCount = playtimeDiagnostics.WholeDayCount;
            snapshot.PlayerWorldPlaytimeReadFailed = playtimeDiagnostics.ReadFailed;
            snapshot.PlayerWorldPlaytimeWriteFailed = playtimeDiagnostics.WriteFailed;
            snapshot.PlayerWorldPlaytimeLastDeltaGameTicks = playtimeDiagnostics.LastDeltaGameTicks;
            snapshot.PlayerWorldPlaytimeLastSkippedDeltaReason = playtimeDiagnostics.LastSkippedDeltaReason;
            snapshot.PlayerWorldPlaytimeLastSampleUtc = playtimeDiagnostics.LastSampleUtc;
            snapshot.PlayerWorldPlaytimeLastWriteUtc = playtimeDiagnostics.LastWriteUtc;
            var explorationDiagnostics = PlayerWorldExplorationDiagnostics.GetSnapshot();
            snapshot.PlayerWorldExplorationLastStatus = explorationDiagnostics.LastStatus;
            snapshot.PlayerWorldExplorationLastMessage = explorationDiagnostics.LastMessage;
            snapshot.PlayerWorldExplorationLastPairId = explorationDiagnostics.LastPairId;
            snapshot.PlayerWorldExplorationWorldWidth = explorationDiagnostics.WorldWidth;
            snapshot.PlayerWorldExplorationWorldHeight = explorationDiagnostics.WorldHeight;
            snapshot.PlayerWorldExplorationTotalTileCount = explorationDiagnostics.TotalTileCount;
            snapshot.PlayerWorldExplorationRevealedTileCount = explorationDiagnostics.RevealedTileCount;
            snapshot.PlayerWorldExplorationWorkingRevealedTileCount = explorationDiagnostics.WorkingRevealedTileCount;
            snapshot.PlayerWorldExplorationScannedTileCount = explorationDiagnostics.ScannedTileCount;
            snapshot.PlayerWorldExplorationNextTileIndex = explorationDiagnostics.NextTileIndex;
            snapshot.PlayerWorldExplorationLastScannedTileBudget = explorationDiagnostics.LastScannedTileBudget;
            snapshot.PlayerWorldExplorationScanMode = explorationDiagnostics.ScanMode;
            snapshot.PlayerWorldExplorationControlState = explorationDiagnostics.ControlState;
            snapshot.PlayerWorldExplorationPausedByUser = explorationDiagnostics.PausedByUser;
            snapshot.PlayerWorldExplorationIdleComplete = explorationDiagnostics.IdleComplete;
            snapshot.PlayerWorldExplorationLastScanElapsedMs = explorationDiagnostics.LastScanElapsedMs;
            snapshot.PlayerWorldExplorationLastScanTileCount = explorationDiagnostics.LastScanTileCount;
            snapshot.PlayerWorldExplorationCurrentTimeBudgetMs = explorationDiagnostics.CurrentTimeBudgetMs;
            snapshot.PlayerWorldExplorationCurrentCadenceTicks = explorationDiagnostics.CurrentCadenceTicks;
            snapshot.PlayerWorldExplorationBackoffApplied = explorationDiagnostics.BackoffApplied;
            snapshot.PlayerWorldExplorationLastUserCommand = explorationDiagnostics.LastUserCommand;
            snapshot.PlayerWorldExplorationAutoRescanDisabled = explorationDiagnostics.AutoRescanDisabled;
            snapshot.PlayerWorldExplorationRevealedPercent = explorationDiagnostics.RevealedPercent;
            snapshot.PlayerWorldExplorationScanComplete = explorationDiagnostics.ScanComplete;
            snapshot.PlayerWorldExplorationReadFailed = explorationDiagnostics.ReadFailed;
            snapshot.PlayerWorldExplorationWriteFailed = explorationDiagnostics.WriteFailed;
            snapshot.PlayerWorldExplorationLastScanUtc = explorationDiagnostics.LastScanUtc;
            snapshot.PlayerWorldExplorationLastCompletedScanUtc = explorationDiagnostics.LastCompletedScanUtc;
            snapshot.PlayerWorldExplorationLastWriteUtc = explorationDiagnostics.LastWriteUtc;
            var mapMarkerDiagnostics = PlayerWorldMapMarkerDiagnostics.GetSnapshot();
            snapshot.PlayerWorldMapMarkersEnabled = source.SettingsSnapshot != null && source.SettingsSnapshot.MapCustomMarkersEnabled;
            snapshot.PlayerWorldMapMarkersLastStatus = mapMarkerDiagnostics.LastStatus;
            snapshot.PlayerWorldMapMarkersLastMessage = mapMarkerDiagnostics.LastMessage;
            snapshot.PlayerWorldMapMarkersLastPairId = mapMarkerDiagnostics.LastPairId;
            snapshot.PlayerWorldMapMarkersCount = mapMarkerDiagnostics.MarkerCount;
            snapshot.PlayerWorldMapMarkersReadFailed = mapMarkerDiagnostics.ReadFailed;
            snapshot.PlayerWorldMapMarkersWriteFailed = mapMarkerDiagnostics.WriteFailed;
            snapshot.PlayerWorldMapMarkersLimitExceeded = mapMarkerDiagnostics.LimitExceeded;
            snapshot.PlayerWorldMapMarkersCulledByCacheLimit = mapMarkerDiagnostics.CulledByCacheLimit;
            snapshot.PlayerWorldMapMarkersLastOperation = mapMarkerDiagnostics.LastOperation;
            snapshot.PlayerWorldMapMarkersLastUiAction = mapMarkerDiagnostics.LastUiAction;
            snapshot.PlayerWorldMapMarkersLastJumpResult = mapMarkerDiagnostics.LastJumpResult;
            snapshot.MapMarkerLastJumpRequestedTileX = mapMarkerDiagnostics.LastJumpRequestedTileX;
            snapshot.MapMarkerLastJumpRequestedTileY = mapMarkerDiagnostics.LastJumpRequestedTileY;
            snapshot.MapMarkerLastJumpWrittenMapPosX = mapMarkerDiagnostics.LastJumpWrittenMapPosX;
            snapshot.MapMarkerLastJumpWrittenMapPosY = mapMarkerDiagnostics.LastJumpWrittenMapPosY;
            snapshot.MapMarkerLastJumpScale = mapMarkerDiagnostics.LastJumpScale;
            snapshot.MapMarkerLastJumpReleasedUiCapture = mapMarkerDiagnostics.LastJumpReleasedUiCapture;
            snapshot.MapMarkerLastJumpClearedPanState = mapMarkerDiagnostics.LastJumpClearedPanState;
            snapshot.MapMarkerLastJumpConsumedButtonPulse = mapMarkerDiagnostics.LastJumpConsumedButtonPulse;
            snapshot.MapMarkerLastJumpVanillaMapInputHandoff = mapMarkerDiagnostics.LastJumpVanillaMapInputHandoff;
            snapshot.MapMarkerLastBlockedReason = mapMarkerDiagnostics.LastBlockedReason;
            snapshot.MapMarkerLastTransformRoute = mapMarkerDiagnostics.LastTransformRoute;
            snapshot.MapMarkerLastTransformScreenWidth = mapMarkerDiagnostics.LastTransformScreenWidth;
            snapshot.MapMarkerLastTransformScreenHeight = mapMarkerDiagnostics.LastTransformScreenHeight;
            snapshot.MapMarkerLastTransformMapTopLeftX = mapMarkerDiagnostics.LastTransformMapTopLeftX;
            snapshot.MapMarkerLastTransformMapTopLeftY = mapMarkerDiagnostics.LastTransformMapTopLeftY;
            snapshot.MapMarkerLastTransformScale = mapMarkerDiagnostics.LastTransformScale;
            snapshot.MapMarkerLastTransformMapFullscreenPosX = mapMarkerDiagnostics.LastTransformMapFullscreenPosX;
            snapshot.MapMarkerLastTransformMapFullscreenPosY = mapMarkerDiagnostics.LastTransformMapFullscreenPosY;
            snapshot.MapMarkerLastTransformGameUpdateCount = mapMarkerDiagnostics.LastTransformGameUpdateCount;
            snapshot.MapMarkerLastTransformUtc = mapMarkerDiagnostics.LastTransformUtc;
            snapshot.MapMarkerLastRightClickMouseX = mapMarkerDiagnostics.LastRightClickMouseX;
            snapshot.MapMarkerLastRightClickMouseY = mapMarkerDiagnostics.LastRightClickMouseY;
            snapshot.MapMarkerLastRightClickTileX = mapMarkerDiagnostics.LastRightClickTileX;
            snapshot.MapMarkerLastRightClickTileY = mapMarkerDiagnostics.LastRightClickTileY;
            snapshot.MapMarkerLastRightClickTransformSource = mapMarkerDiagnostics.LastRightClickTransformSource;
            snapshot.MapMarkerLastRightClickFallbackReason = mapMarkerDiagnostics.LastRightClickFallbackReason;
            snapshot.MapMarkerLastRightClickMapFullscreenPosX = mapMarkerDiagnostics.LastRightClickMapFullscreenPosX;
            snapshot.MapMarkerLastRightClickMapFullscreenPosY = mapMarkerDiagnostics.LastRightClickMapFullscreenPosY;
            snapshot.MapMarkerLastRightClickMapScale = mapMarkerDiagnostics.LastRightClickMapScale;
            snapshot.MapMarkerLastRightClickTransformAgeUpdates = mapMarkerDiagnostics.LastRightClickTransformAgeUpdates;
            snapshot.PlayerWorldMapMarkersUiOnlyActionCount = mapMarkerDiagnostics.UiOnlyActionCount;
            snapshot.MapMarkerPickerOpen = mapMarkerDiagnostics.PickerOpen;
            snapshot.MapMarkerPickerAnchorScreenX = mapMarkerDiagnostics.PickerAnchorScreenX;
            snapshot.MapMarkerPickerAnchorScreenY = mapMarkerDiagnostics.PickerAnchorScreenY;
            snapshot.MapMarkerPickerPanelX = mapMarkerDiagnostics.PickerPanelX;
            snapshot.MapMarkerPickerPanelY = mapMarkerDiagnostics.PickerPanelY;
            snapshot.MapMarkerPickerPanelClamped = mapMarkerDiagnostics.PickerPanelClamped;
            snapshot.MapMarkerPickerLastDraw = mapMarkerDiagnostics.PickerLastDraw;
            snapshot.MapMarkerPickerLastFullscreenDraw = mapMarkerDiagnostics.PickerLastFullscreenDraw;
            snapshot.MapMarkerPickerDrawRoute = mapMarkerDiagnostics.PickerDrawRoute;
            snapshot.MapMarkerPickerDrawSkippedReason = mapMarkerDiagnostics.PickerDrawSkippedReason;
            snapshot.MapMarkerPickerLastClick = mapMarkerDiagnostics.PickerLastClick;
            snapshot.MapMarkerPickerLastCloseReason = mapMarkerDiagnostics.PickerLastCloseReason;
            snapshot.PlayerWorldMapMarkersLastReadUtc = mapMarkerDiagnostics.LastReadUtc;
            snapshot.PlayerWorldMapMarkersLastWriteUtc = mapMarkerDiagnostics.LastWriteUtc;
            snapshot.MapMarkerTraceEventsPath = PlayerWorldMapMarkerTraceRecorder.TraceEventsPathForSnapshot;
            snapshot.MapMarkerLastTraceEventWrittenAtUtc = PlayerWorldMapMarkerTraceRecorder.LastTraceEventWrittenAtUtc;
            snapshot.MapMarkerLastTraceEventType = PlayerWorldMapMarkerTraceRecorder.LastTraceEventType;
            snapshot.MapMarkerLastTraceMarkerId = PlayerWorldMapMarkerTraceRecorder.LastTraceMarkerId;
            var directionHintDiagnostics = MapDirectionHintDiagnostics.GetSnapshot();
            snapshot.MapDirectionHintTargetScanCadenceTicks = MapDirectionHintTargetService.ScanCadenceTicks;
            snapshot.MapRareCreatureDirectionEnabled = directionHintDiagnostics.MapRareCreatureDirectionEnabled;
            snapshot.MapRareCreatureDirectionStatus = directionHintDiagnostics.MapRareCreatureDirectionStatus;
            snapshot.MapRareCreatureDirectionMessage = directionHintDiagnostics.MapRareCreatureDirectionMessage;
            snapshot.MapRareCreatureDirectionGateReason = directionHintDiagnostics.MapRareCreatureDirectionGateReason;
            snapshot.MapRareCreatureDirectionHasLifeformAnalyzer = directionHintDiagnostics.MapRareCreatureDirectionHasLifeformAnalyzer;
            snapshot.MapRareCreatureDirectionInfoAccessoryHidden = directionHintDiagnostics.MapRareCreatureDirectionInfoAccessoryHidden;
            snapshot.MapRareCreatureDirectionTargetActive = directionHintDiagnostics.MapRareCreatureDirectionTargetActive;
            snapshot.MapRareCreatureDirectionTargetWhoAmI = directionHintDiagnostics.MapRareCreatureDirectionTargetWhoAmI;
            snapshot.MapRareCreatureDirectionTargetType = directionHintDiagnostics.MapRareCreatureDirectionTargetType;
            snapshot.MapRareCreatureDirectionTargetName = directionHintDiagnostics.MapRareCreatureDirectionTargetName;
            snapshot.MapRareCreatureDirectionTargetRarity = directionHintDiagnostics.MapRareCreatureDirectionTargetRarity;
            snapshot.MapRareCreatureDirectionTargetWorldX = directionHintDiagnostics.MapRareCreatureDirectionTargetWorldX;
            snapshot.MapRareCreatureDirectionTargetWorldY = directionHintDiagnostics.MapRareCreatureDirectionTargetWorldY;
            snapshot.MapRareCreatureDirectionOnScreen = directionHintDiagnostics.MapRareCreatureDirectionOnScreen;
            snapshot.MapRareCreatureDirectionShouldDrawLabel = directionHintDiagnostics.MapRareCreatureDirectionShouldDrawLabel;
            snapshot.MapRareCreatureDirectionDistancePixels = directionHintDiagnostics.MapRareCreatureDirectionDistancePixels;
            snapshot.MapRareCreatureDirectionDistanceText = directionHintDiagnostics.MapRareCreatureDirectionDistanceText;
            snapshot.MapRareCreatureDirectionArrowScreenX = directionHintDiagnostics.MapRareCreatureDirectionArrowScreenX;
            snapshot.MapRareCreatureDirectionArrowScreenY = directionHintDiagnostics.MapRareCreatureDirectionArrowScreenY;
            snapshot.MapRareCreatureDirectionDirectionX = directionHintDiagnostics.MapRareCreatureDirectionDirectionX;
            snapshot.MapRareCreatureDirectionDirectionY = directionHintDiagnostics.MapRareCreatureDirectionDirectionY;
            snapshot.MapRareCreatureDirectionArrowGlyph = directionHintDiagnostics.MapRareCreatureDirectionArrowGlyph;
            snapshot.MapRareCreatureDirectionLabelLine1 = directionHintDiagnostics.MapRareCreatureDirectionLabelLine1;
            snapshot.MapRareCreatureDirectionLabelLine2 = directionHintDiagnostics.MapRareCreatureDirectionLabelLine2;
            snapshot.MapRareCreatureDirectionLastScanTick = directionHintDiagnostics.MapRareCreatureDirectionLastScanTick;
            snapshot.MapRareCreatureDirectionLastScanAgeTicks =
                directionHintDiagnostics.MapRareCreatureDirectionLastScanTick < 0L || State == null
                    ? -1L
                    : Math.Max(0L, State.UpdateCount - directionHintDiagnostics.MapRareCreatureDirectionLastScanTick);
            snapshot.MapRareCreatureDirectionDrawStatus = directionHintDiagnostics.MapRareCreatureDirectionDrawStatus;
            snapshot.MapRareCreatureDirectionLastTargetUtc = directionHintDiagnostics.MapRareCreatureDirectionLastTargetUtc;
            snapshot.MapRareCreatureDirectionLastDrawUtc = directionHintDiagnostics.MapRareCreatureDirectionLastDrawUtc;
            snapshot.MapTravellingMerchantDirectionEnabled = directionHintDiagnostics.MapTravellingMerchantDirectionEnabled;
            snapshot.MapTravellingMerchantDirectionStatus = directionHintDiagnostics.MapTravellingMerchantDirectionStatus;
            snapshot.MapTravellingMerchantDirectionMessage = directionHintDiagnostics.MapTravellingMerchantDirectionMessage;
            snapshot.MapTravellingMerchantDirectionTargetActive = directionHintDiagnostics.MapTravellingMerchantDirectionTargetActive;
            snapshot.MapTravellingMerchantDirectionTargetWhoAmI = directionHintDiagnostics.MapTravellingMerchantDirectionTargetWhoAmI;
            snapshot.MapTravellingMerchantDirectionTargetType = directionHintDiagnostics.MapTravellingMerchantDirectionTargetType;
            snapshot.MapTravellingMerchantDirectionTargetName = directionHintDiagnostics.MapTravellingMerchantDirectionTargetName;
            snapshot.MapTravellingMerchantDirectionTargetWorldX = directionHintDiagnostics.MapTravellingMerchantDirectionTargetWorldX;
            snapshot.MapTravellingMerchantDirectionTargetWorldY = directionHintDiagnostics.MapTravellingMerchantDirectionTargetWorldY;
            snapshot.MapTravellingMerchantDirectionOnScreen = directionHintDiagnostics.MapTravellingMerchantDirectionOnScreen;
            snapshot.MapTravellingMerchantDirectionDistancePixels = directionHintDiagnostics.MapTravellingMerchantDirectionDistancePixels;
            snapshot.MapTravellingMerchantDirectionDistanceText = directionHintDiagnostics.MapTravellingMerchantDirectionDistanceText;
            snapshot.MapTravellingMerchantDirectionEdgeScreenX = directionHintDiagnostics.MapTravellingMerchantDirectionEdgeScreenX;
            snapshot.MapTravellingMerchantDirectionEdgeScreenY = directionHintDiagnostics.MapTravellingMerchantDirectionEdgeScreenY;
            snapshot.MapTravellingMerchantDirectionDirectionX = directionHintDiagnostics.MapTravellingMerchantDirectionDirectionX;
            snapshot.MapTravellingMerchantDirectionDirectionY = directionHintDiagnostics.MapTravellingMerchantDirectionDirectionY;
            snapshot.MapTravellingMerchantDirectionLabelLine1 = directionHintDiagnostics.MapTravellingMerchantDirectionLabelLine1;
            snapshot.MapTravellingMerchantDirectionLabelLine2 = directionHintDiagnostics.MapTravellingMerchantDirectionLabelLine2;
            snapshot.MapTravellingMerchantDirectionLabelLine3 = directionHintDiagnostics.MapTravellingMerchantDirectionLabelLine3;
            snapshot.MapTravellingMerchantDirectionTownLabel = directionHintDiagnostics.MapTravellingMerchantDirectionTownLabel;
            snapshot.MapTravellingMerchantDirectionTownLabelSource = directionHintDiagnostics.MapTravellingMerchantDirectionTownLabelSource;
            snapshot.MapTravellingMerchantDirectionTownLabelConfidence = directionHintDiagnostics.MapTravellingMerchantDirectionTownLabelConfidence;
            snapshot.MapTravellingMerchantDirectionMatchedPylonType = directionHintDiagnostics.MapTravellingMerchantDirectionMatchedPylonType;
            snapshot.MapTravellingMerchantDirectionMatchedPylonDistanceTiles = directionHintDiagnostics.MapTravellingMerchantDirectionMatchedPylonDistanceTiles;
            snapshot.MapTravellingMerchantDirectionNearbyTownNpcCount = directionHintDiagnostics.MapTravellingMerchantDirectionNearbyTownNpcCount;
            snapshot.MapTravellingMerchantDirectionLastScanTick = directionHintDiagnostics.MapTravellingMerchantDirectionLastScanTick;
            snapshot.MapTravellingMerchantDirectionLastScanAgeTicks =
                directionHintDiagnostics.MapTravellingMerchantDirectionLastScanTick < 0L || State == null
                    ? -1L
                    : Math.Max(0L, State.UpdateCount - directionHintDiagnostics.MapTravellingMerchantDirectionLastScanTick);
            snapshot.MapTravellingMerchantDirectionDrawStatus = directionHintDiagnostics.MapTravellingMerchantDirectionDrawStatus;
            snapshot.MapTravellingMerchantDirectionLastTargetUtc = directionHintDiagnostics.MapTravellingMerchantDirectionLastTargetUtc;
            snapshot.MapTravellingMerchantDirectionLastDrawUtc = directionHintDiagnostics.MapTravellingMerchantDirectionLastDrawUtc;
            var footprintDiagnostics = PlayerWorldFootprintDiagnostics.GetSnapshot();
            var footprintRetainedTicks = Math.Max(0L, footprintDiagnostics.TimelineEndTicks - footprintDiagnostics.TimelineStartTicks);
            var footprintTicksPerHour = PlayerWorldFootprintConstants.TicksPerSecond * 60L * 60L;
            snapshot.MapFootprintsDisplayEnabled = footprintDiagnostics.MapFootprintsDisplayEnabled;
            snapshot.PlayerWorldFootprintsLastStatus = footprintDiagnostics.LastStatus;
            snapshot.PlayerWorldFootprintsLastDecision = footprintDiagnostics.LastDecision;
            snapshot.PlayerWorldFootprintsLastMessage = footprintDiagnostics.LastMessage;
            snapshot.PlayerWorldFootprintsLastPairId = footprintDiagnostics.LastPairId;
            snapshot.PlayerWorldFootprintsIdentityResolved = footprintDiagnostics.IdentityResolved;
            snapshot.PlayerWorldFootprintsIsRecording = footprintDiagnostics.IsRecording;
            snapshot.PlayerWorldFootprintsReadFailed = footprintDiagnostics.ReadFailed;
            snapshot.PlayerWorldFootprintsWriteFailed = footprintDiagnostics.WriteFailed;
            snapshot.PlayerWorldFootprintsRetentionTrimmed = footprintDiagnostics.RetentionTrimmed;
            snapshot.PlayerWorldFootprintsMaxRetainedHours = PlayerWorldFootprintConstants.MaxRetainedHours;
            snapshot.PlayerWorldFootprintsRetainedHours = footprintTicksPerHour <= 0L ? 0d : footprintRetainedTicks / (double)footprintTicksPerHour;
            snapshot.PlayerWorldFootprintsSegmentCount = footprintDiagnostics.SegmentCount;
            snapshot.PlayerWorldFootprintsPointCount = footprintDiagnostics.PointCount;
            snapshot.PlayerWorldFootprintsBreakCount = footprintDiagnostics.BreakCount;
            snapshot.PlayerWorldFootprintsTimelineStartTicks = footprintDiagnostics.TimelineStartTicks;
            snapshot.PlayerWorldFootprintsTimelineEndTicks = footprintDiagnostics.TimelineEndTicks;
            snapshot.PlayerWorldFootprintsLastPointTileX = footprintDiagnostics.LastPointTileX;
            snapshot.PlayerWorldFootprintsLastPointTileY = footprintDiagnostics.LastPointTileY;
            snapshot.PlayerWorldFootprintsLastPointDurationTicks = footprintDiagnostics.LastPointDurationTicks;
            snapshot.PlayerWorldFootprintsLastRecordRuntimeTick = footprintDiagnostics.LastRecordRuntimeTick;
            snapshot.PlayerWorldFootprintsLastFlushStatus = footprintDiagnostics.LastFlushStatus;
            snapshot.PlayerWorldFootprintsLastReadUtc = footprintDiagnostics.LastReadUtc;
            snapshot.PlayerWorldFootprintsLastRecordUtc = footprintDiagnostics.LastRecordUtc;
            snapshot.PlayerWorldFootprintsLastWriteUtc = footprintDiagnostics.LastWriteUtc;
            snapshot.MapFootprintsRenderCacheStatus = footprintDiagnostics.MapFootprintsRenderCacheStatus;
            snapshot.MapFootprintsRenderCacheMessage = footprintDiagnostics.MapFootprintsRenderCacheMessage;
            snapshot.MapFootprintsRenderCachePairId = footprintDiagnostics.MapFootprintsRenderCachePairId;
            snapshot.MapFootprintsRenderCacheSource = footprintDiagnostics.MapFootprintsRenderCacheSource;
            snapshot.MapFootprintsRenderCacheSegmentCount = footprintDiagnostics.MapFootprintsRenderCacheSegmentCount;
            snapshot.MapFootprintsRenderCachePointCount = footprintDiagnostics.MapFootprintsRenderCachePointCount;
            snapshot.MapFootprintsRenderCacheLineCount = footprintDiagnostics.MapFootprintsRenderCacheLineCount;
            snapshot.MapFootprintsRenderCacheDataSignature = footprintDiagnostics.MapFootprintsRenderCacheDataSignature;
            snapshot.MapFootprintsRenderCacheLimitHit = footprintDiagnostics.MapFootprintsRenderCacheLimitHit;
            snapshot.MapFootprintsLastDrawStatus = footprintDiagnostics.MapFootprintsLastDrawStatus;
            snapshot.MapFootprintsLastDrawMessage = footprintDiagnostics.MapFootprintsLastDrawMessage;
            snapshot.MapFootprintsLastDrawPairId = footprintDiagnostics.MapFootprintsLastDrawPairId;
            snapshot.MapFootprintsCachedLineCount = footprintDiagnostics.MapFootprintsCachedLineCount;
            snapshot.MapFootprintsDrawnLineCount = footprintDiagnostics.MapFootprintsDrawnLineCount;
            snapshot.MapFootprintsCulledLineCount = footprintDiagnostics.MapFootprintsCulledLineCount;
            snapshot.MapFootprintsThinnedLineCount = footprintDiagnostics.MapFootprintsThinnedLineCount;
            snapshot.MapFootprintsDrawLimitSkippedLineCount = footprintDiagnostics.MapFootprintsDrawLimitSkippedLineCount;
            snapshot.MapFootprintsDrawLimitHit = footprintDiagnostics.MapFootprintsDrawLimitHit;
            snapshot.MapFootprintsLastDrawUtc = footprintDiagnostics.MapFootprintsLastDrawUtc;
            snapshot.MapFootprintsDrawRoute = footprintDiagnostics.MapFootprintsDrawRoute;
            snapshot.MapFootprintsDrawScreenWidth = footprintDiagnostics.MapFootprintsDrawScreenWidth;
            snapshot.MapFootprintsDrawScreenHeight = footprintDiagnostics.MapFootprintsDrawScreenHeight;
            snapshot.MapFootprintsDrawGameUpdateCount = footprintDiagnostics.MapFootprintsDrawGameUpdateCount;
            snapshot.MapFootprintsDrawMapFullscreenPosX = footprintDiagnostics.MapFootprintsDrawMapFullscreenPosX;
            snapshot.MapFootprintsDrawMapFullscreenPosY = footprintDiagnostics.MapFootprintsDrawMapFullscreenPosY;
            snapshot.MapFootprintsDrawMapFullscreenScale = footprintDiagnostics.MapFootprintsDrawMapFullscreenScale;
            snapshot.MapFootprintsDrawTransformMapPositionX = footprintDiagnostics.MapFootprintsDrawTransformMapPositionX;
            snapshot.MapFootprintsDrawTransformMapPositionY = footprintDiagnostics.MapFootprintsDrawTransformMapPositionY;
            snapshot.MapFootprintsDrawTransformMapOffsetX = footprintDiagnostics.MapFootprintsDrawTransformMapOffsetX;
            snapshot.MapFootprintsDrawTransformMapOffsetY = footprintDiagnostics.MapFootprintsDrawTransformMapOffsetY;
            snapshot.MapFootprintsDrawTransformMapScale = footprintDiagnostics.MapFootprintsDrawTransformMapScale;
            snapshot.MapFootprintsDrawTransformOpacity = footprintDiagnostics.MapFootprintsDrawTransformOpacity;
            snapshot.MapFootprintsDrawCommandSampleCount = footprintDiagnostics.MapFootprintsDrawCommandSampleCount;
            snapshot.MapFootprintsDrawAbnormalLongLineCount = footprintDiagnostics.MapFootprintsDrawAbnormalLongLineCount;
            snapshot.MapFootprintsDrawLongLineThresholdPixels = footprintDiagnostics.MapFootprintsDrawLongLineThresholdPixels;
            snapshot.MapFootprintsDrawMaxLinePixels = footprintDiagnostics.MapFootprintsDrawMaxLinePixels;
            snapshot.MapFootprintsDrawMaxLineSegmentIndex = footprintDiagnostics.MapFootprintsDrawMaxLineSegmentIndex;
            snapshot.MapFootprintsDrawFirstSegmentIndex = footprintDiagnostics.MapFootprintsDrawFirstSegmentIndex;
            snapshot.MapFootprintsDrawFirstStartTileX = footprintDiagnostics.MapFootprintsDrawFirstStartTileX;
            snapshot.MapFootprintsDrawFirstStartTileY = footprintDiagnostics.MapFootprintsDrawFirstStartTileY;
            snapshot.MapFootprintsDrawFirstEndTileX = footprintDiagnostics.MapFootprintsDrawFirstEndTileX;
            snapshot.MapFootprintsDrawFirstEndTileY = footprintDiagnostics.MapFootprintsDrawFirstEndTileY;
            snapshot.MapFootprintsDrawFirstStartScreenX = footprintDiagnostics.MapFootprintsDrawFirstStartScreenX;
            snapshot.MapFootprintsDrawFirstStartScreenY = footprintDiagnostics.MapFootprintsDrawFirstStartScreenY;
            snapshot.MapFootprintsDrawFirstEndScreenX = footprintDiagnostics.MapFootprintsDrawFirstEndScreenX;
            snapshot.MapFootprintsDrawFirstEndScreenY = footprintDiagnostics.MapFootprintsDrawFirstEndScreenY;
            snapshot.MapFootprintsDrawLastSegmentIndex = footprintDiagnostics.MapFootprintsDrawLastSegmentIndex;
            snapshot.MapFootprintsDrawLastStartTileX = footprintDiagnostics.MapFootprintsDrawLastStartTileX;
            snapshot.MapFootprintsDrawLastStartTileY = footprintDiagnostics.MapFootprintsDrawLastStartTileY;
            snapshot.MapFootprintsDrawLastEndTileX = footprintDiagnostics.MapFootprintsDrawLastEndTileX;
            snapshot.MapFootprintsDrawLastEndTileY = footprintDiagnostics.MapFootprintsDrawLastEndTileY;
            snapshot.MapFootprintsDrawLastStartScreenX = footprintDiagnostics.MapFootprintsDrawLastStartScreenX;
            snapshot.MapFootprintsDrawLastStartScreenY = footprintDiagnostics.MapFootprintsDrawLastStartScreenY;
            snapshot.MapFootprintsDrawLastEndScreenX = footprintDiagnostics.MapFootprintsDrawLastEndScreenX;
            snapshot.MapFootprintsDrawLastEndScreenY = footprintDiagnostics.MapFootprintsDrawLastEndScreenY;
            snapshot.MapFootprintsDrawLongestSegmentIndex = footprintDiagnostics.MapFootprintsDrawLongestSegmentIndex;
            snapshot.MapFootprintsDrawLongestStartTileX = footprintDiagnostics.MapFootprintsDrawLongestStartTileX;
            snapshot.MapFootprintsDrawLongestStartTileY = footprintDiagnostics.MapFootprintsDrawLongestStartTileY;
            snapshot.MapFootprintsDrawLongestEndTileX = footprintDiagnostics.MapFootprintsDrawLongestEndTileX;
            snapshot.MapFootprintsDrawLongestEndTileY = footprintDiagnostics.MapFootprintsDrawLongestEndTileY;
            snapshot.MapFootprintsDrawLongestStartScreenX = footprintDiagnostics.MapFootprintsDrawLongestStartScreenX;
            snapshot.MapFootprintsDrawLongestStartScreenY = footprintDiagnostics.MapFootprintsDrawLongestStartScreenY;
            snapshot.MapFootprintsDrawLongestEndScreenX = footprintDiagnostics.MapFootprintsDrawLongestEndScreenX;
            snapshot.MapFootprintsDrawLongestEndScreenY = footprintDiagnostics.MapFootprintsDrawLongestEndScreenY;
            snapshot.MapFootprintsPlaybackOverlayStatus = footprintDiagnostics.MapFootprintsPlaybackOverlayStatus;
            snapshot.MapFootprintsPlaybackOverlayMessage = footprintDiagnostics.MapFootprintsPlaybackOverlayMessage;
            snapshot.MapFootprintsPlaybackPairId = footprintDiagnostics.MapFootprintsPlaybackPairId;
            snapshot.MapFootprintsPlaybackPaused = footprintDiagnostics.MapFootprintsPlaybackPaused;
            snapshot.MapFootprintsPlaybackRate = footprintDiagnostics.MapFootprintsPlaybackRate;
            snapshot.MapFootprintsPlaybackCursorTicks = footprintDiagnostics.MapFootprintsPlaybackCursorTicks;
            snapshot.MapFootprintsPlaybackTimelineStartTicks = footprintDiagnostics.MapFootprintsPlaybackTimelineStartTicks;
            snapshot.MapFootprintsPlaybackLatestTicks = footprintDiagnostics.MapFootprintsPlaybackLatestTicks;
            snapshot.MapFootprintsPlaybackProgress = footprintDiagnostics.MapFootprintsPlaybackProgress;
            snapshot.MapFootprintsPlaybackAtLatest = footprintDiagnostics.MapFootprintsPlaybackAtLatest;
            snapshot.MapFootprintsPlaybackDragging = footprintDiagnostics.MapFootprintsPlaybackDragging;
            snapshot.MapFootprintsPlaybackMouseCaptured = footprintDiagnostics.MapFootprintsPlaybackMouseCaptured;
            snapshot.MapFootprintsPlaybackBarHovered = footprintDiagnostics.MapFootprintsPlaybackBarHovered;
            snapshot.MapFootprintsPlaybackLastInteraction = footprintDiagnostics.MapFootprintsPlaybackLastInteraction;
            snapshot.MapFootprintsPlaybackLastUpdateUtc = footprintDiagnostics.MapFootprintsPlaybackLastUpdateUtc;
            snapshot.MapFootprintsPlaybackPrefixHitTarget = footprintDiagnostics.MapFootprintsPlaybackPrefixHitTarget;
            snapshot.MapFootprintsPlaybackPrefixMouseReadMode = footprintDiagnostics.MapFootprintsPlaybackPrefixMouseReadMode;
            snapshot.MapFootprintsPlaybackPrefixMouseX = footprintDiagnostics.MapFootprintsPlaybackPrefixMouseX;
            snapshot.MapFootprintsPlaybackPrefixMouseY = footprintDiagnostics.MapFootprintsPlaybackPrefixMouseY;
            snapshot.MapFootprintsPlaybackPrefixMouseReadAvailable = footprintDiagnostics.MapFootprintsPlaybackPrefixMouseReadAvailable;
            snapshot.MapFootprintsPlaybackPrefixBarHovered = footprintDiagnostics.MapFootprintsPlaybackPrefixBarHovered;
            snapshot.MapFootprintsPlaybackPrefixMouseCaptured = footprintDiagnostics.MapFootprintsPlaybackPrefixMouseCaptured;
            snapshot.MapFootprintsPlaybackPrefixClickConsumed = footprintDiagnostics.MapFootprintsPlaybackPrefixClickConsumed;
            snapshot.MapFootprintsPlaybackPrefixScrollConsumed = footprintDiagnostics.MapFootprintsPlaybackPrefixScrollConsumed;
            snapshot.MapFootprintsPlaybackPrefixShouldSuppressLeftInput = footprintDiagnostics.MapFootprintsPlaybackPrefixShouldSuppressLeftInput;
            snapshot.MapFootprintsPlaybackPrefixShouldSuppressNonLeftInput = footprintDiagnostics.MapFootprintsPlaybackPrefixShouldSuppressNonLeftInput;
            snapshot.MapFootprintsPlaybackPrefixShouldClearPanState = footprintDiagnostics.MapFootprintsPlaybackPrefixShouldClearPanState;
            snapshot.MapFootprintsPlaybackPrefixLeftInputSuppressed = footprintDiagnostics.MapFootprintsPlaybackPrefixLeftInputSuppressed;
            snapshot.MapFootprintsPlaybackPrefixNonLeftInputSuppressed = footprintDiagnostics.MapFootprintsPlaybackPrefixNonLeftInputSuppressed;
            snapshot.MapFootprintsPlaybackPrefixScrollSuppressed = footprintDiagnostics.MapFootprintsPlaybackPrefixScrollSuppressed;
            snapshot.MapFootprintsPlaybackPrefixPanStateClearAttempted = footprintDiagnostics.MapFootprintsPlaybackPrefixPanStateClearAttempted;
            snapshot.MapFootprintsPlaybackPrefixPanStateClearSucceeded = footprintDiagnostics.MapFootprintsPlaybackPrefixPanStateClearSucceeded;
            snapshot.MapFootprintsPlaybackPrefixLeftDown = footprintDiagnostics.MapFootprintsPlaybackPrefixLeftDown;
            snapshot.MapFootprintsPlaybackPrefixLeftPressed = footprintDiagnostics.MapFootprintsPlaybackPrefixLeftPressed;
            snapshot.MapFootprintsPlaybackPrefixLeftReleased = footprintDiagnostics.MapFootprintsPlaybackPrefixLeftReleased;
            snapshot.MapFootprintsPlaybackPrefixScrollDelta = footprintDiagnostics.MapFootprintsPlaybackPrefixScrollDelta;
            snapshot.MapFootprintsPlaybackPrefixGameUpdateCount = footprintDiagnostics.MapFootprintsPlaybackPrefixGameUpdateCount;
            snapshot.MapFootprintsPlaybackPrefixMainMouseLeftBefore = footprintDiagnostics.MapFootprintsPlaybackPrefixMainMouseLeftBefore;
            snapshot.MapFootprintsPlaybackPrefixMainMouseLeftAfter = footprintDiagnostics.MapFootprintsPlaybackPrefixMainMouseLeftAfter;
            snapshot.MapFootprintsPlaybackPrefixMainMouseLeftReleaseBefore = footprintDiagnostics.MapFootprintsPlaybackPrefixMainMouseLeftReleaseBefore;
            snapshot.MapFootprintsPlaybackPrefixMainMouseLeftReleaseAfter = footprintDiagnostics.MapFootprintsPlaybackPrefixMainMouseLeftReleaseAfter;
            snapshot.MapFootprintsPlaybackPrefixMainMouseRightBefore = footprintDiagnostics.MapFootprintsPlaybackPrefixMainMouseRightBefore;
            snapshot.MapFootprintsPlaybackPrefixMainMouseRightAfter = footprintDiagnostics.MapFootprintsPlaybackPrefixMainMouseRightAfter;
            snapshot.MapFootprintsPlaybackPrefixMainMouseRightReleaseBefore = footprintDiagnostics.MapFootprintsPlaybackPrefixMainMouseRightReleaseBefore;
            snapshot.MapFootprintsPlaybackPrefixMainMouseRightReleaseAfter = footprintDiagnostics.MapFootprintsPlaybackPrefixMainMouseRightReleaseAfter;
            snapshot.MapFootprintsPlaybackPrefixMainMouseScrollWheelBefore = footprintDiagnostics.MapFootprintsPlaybackPrefixMainMouseScrollWheelBefore;
            snapshot.MapFootprintsPlaybackPrefixMainMouseScrollWheelAfter = footprintDiagnostics.MapFootprintsPlaybackPrefixMainMouseScrollWheelAfter;
            snapshot.MapFootprintsPlaybackPrefixMainOldMouseScrollWheelBefore = footprintDiagnostics.MapFootprintsPlaybackPrefixMainOldMouseScrollWheelBefore;
            snapshot.MapFootprintsPlaybackPrefixMainOldMouseScrollWheelAfter = footprintDiagnostics.MapFootprintsPlaybackPrefixMainOldMouseScrollWheelAfter;
            snapshot.MapFootprintsPlaybackPrefixMainMouseInterfaceBefore = footprintDiagnostics.MapFootprintsPlaybackPrefixMainMouseInterfaceBefore;
            snapshot.MapFootprintsPlaybackPrefixMainMouseInterfaceAfter = footprintDiagnostics.MapFootprintsPlaybackPrefixMainMouseInterfaceAfter;
            snapshot.MapFootprintsPlaybackPrefixMainBlockMouseBefore = footprintDiagnostics.MapFootprintsPlaybackPrefixMainBlockMouseBefore;
            snapshot.MapFootprintsPlaybackPrefixMainBlockMouseAfter = footprintDiagnostics.MapFootprintsPlaybackPrefixMainBlockMouseAfter;
            snapshot.MapFootprintsPlaybackPrefixPlayerMouseInterfaceBefore = footprintDiagnostics.MapFootprintsPlaybackPrefixPlayerMouseInterfaceBefore;
            snapshot.MapFootprintsPlaybackPrefixPlayerMouseInterfaceAfter = footprintDiagnostics.MapFootprintsPlaybackPrefixPlayerMouseInterfaceAfter;
            snapshot.MapFootprintsPlaybackPrefixUtc = footprintDiagnostics.MapFootprintsPlaybackPrefixUtc;
            snapshot.MapFootprintsPlaybackAfterPlayerInputGuardActive = footprintDiagnostics.MapFootprintsPlaybackAfterPlayerInputGuardActive;
            snapshot.MapFootprintsPlaybackAfterPlayerInputShouldSuppressLeftInput = footprintDiagnostics.MapFootprintsPlaybackAfterPlayerInputShouldSuppressLeftInput;
            snapshot.MapFootprintsPlaybackAfterPlayerInputShouldSuppressNonLeftInput = footprintDiagnostics.MapFootprintsPlaybackAfterPlayerInputShouldSuppressNonLeftInput;
            snapshot.MapFootprintsPlaybackAfterPlayerInputReleaseFrame = footprintDiagnostics.MapFootprintsPlaybackAfterPlayerInputReleaseFrame;
            snapshot.MapFootprintsPlaybackAfterPlayerInputMainMouseLeftBefore = footprintDiagnostics.MapFootprintsPlaybackAfterPlayerInputMainMouseLeftBefore;
            snapshot.MapFootprintsPlaybackAfterPlayerInputMainMouseLeftAfter = footprintDiagnostics.MapFootprintsPlaybackAfterPlayerInputMainMouseLeftAfter;
            snapshot.MapFootprintsPlaybackAfterPlayerInputMainMouseLeftReleaseBefore = footprintDiagnostics.MapFootprintsPlaybackAfterPlayerInputMainMouseLeftReleaseBefore;
            snapshot.MapFootprintsPlaybackAfterPlayerInputMainMouseLeftReleaseAfter = footprintDiagnostics.MapFootprintsPlaybackAfterPlayerInputMainMouseLeftReleaseAfter;
            snapshot.MapFootprintsPlaybackAfterPlayerInputMainMouseRightBefore = footprintDiagnostics.MapFootprintsPlaybackAfterPlayerInputMainMouseRightBefore;
            snapshot.MapFootprintsPlaybackAfterPlayerInputMainMouseRightAfter = footprintDiagnostics.MapFootprintsPlaybackAfterPlayerInputMainMouseRightAfter;
            snapshot.MapFootprintsPlaybackAfterPlayerInputMainMouseRightReleaseBefore = footprintDiagnostics.MapFootprintsPlaybackAfterPlayerInputMainMouseRightReleaseBefore;
            snapshot.MapFootprintsPlaybackAfterPlayerInputMainMouseRightReleaseAfter = footprintDiagnostics.MapFootprintsPlaybackAfterPlayerInputMainMouseRightReleaseAfter;
            snapshot.MapFootprintsPlaybackAfterPlayerInputGameUpdateCount = footprintDiagnostics.MapFootprintsPlaybackAfterPlayerInputGameUpdateCount;
            snapshot.MapFootprintsPlaybackAfterPlayerInputUtc = footprintDiagnostics.MapFootprintsPlaybackAfterPlayerInputUtc;
            snapshot.MapFootprintsPlaybackDrawHitTarget = footprintDiagnostics.MapFootprintsPlaybackDrawHitTarget;
            snapshot.MapFootprintsPlaybackDrawMouseReadMode = footprintDiagnostics.MapFootprintsPlaybackDrawMouseReadMode;
            snapshot.MapFootprintsPlaybackDrawMouseX = footprintDiagnostics.MapFootprintsPlaybackDrawMouseX;
            snapshot.MapFootprintsPlaybackDrawMouseY = footprintDiagnostics.MapFootprintsPlaybackDrawMouseY;
            snapshot.MapFootprintsPlaybackDrawMouseReadAvailable = footprintDiagnostics.MapFootprintsPlaybackDrawMouseReadAvailable;
            snapshot.MapFootprintsPlaybackDrawBarHovered = footprintDiagnostics.MapFootprintsPlaybackDrawBarHovered;
            snapshot.MapFootprintsPlaybackDrawMainMouseLeft = footprintDiagnostics.MapFootprintsPlaybackDrawMainMouseLeft;
            snapshot.MapFootprintsPlaybackDrawMainMouseLeftRelease = footprintDiagnostics.MapFootprintsPlaybackDrawMainMouseLeftRelease;
            snapshot.MapFootprintsPlaybackDrawMainMouseRight = footprintDiagnostics.MapFootprintsPlaybackDrawMainMouseRight;
            snapshot.MapFootprintsPlaybackDrawMainMouseRightRelease = footprintDiagnostics.MapFootprintsPlaybackDrawMainMouseRightRelease;
            snapshot.MapFootprintsPlaybackDrawMainMouseScrollWheel = footprintDiagnostics.MapFootprintsPlaybackDrawMainMouseScrollWheel;
            snapshot.MapFootprintsPlaybackDrawMainOldMouseScrollWheel = footprintDiagnostics.MapFootprintsPlaybackDrawMainOldMouseScrollWheel;
            snapshot.MapFootprintsPlaybackDrawMainMouseInterface = footprintDiagnostics.MapFootprintsPlaybackDrawMainMouseInterface;
            snapshot.MapFootprintsPlaybackDrawMainBlockMouse = footprintDiagnostics.MapFootprintsPlaybackDrawMainBlockMouse;
            snapshot.MapFootprintsPlaybackDrawPlayerMouseInterface = footprintDiagnostics.MapFootprintsPlaybackDrawPlayerMouseInterface;
            snapshot.MapFootprintsPlaybackDrawGameUpdateCount = footprintDiagnostics.MapFootprintsPlaybackDrawGameUpdateCount;
            snapshot.MapFootprintsPlaybackDrawUtc = footprintDiagnostics.MapFootprintsPlaybackDrawUtc;
            snapshot.DiagnosticsOverlayVisible = DiagnosticsOverlay.Visible;
            snapshot.DrawCallCount = DiagnosticsOverlay.DrawCallCount;
            snapshot.LastDrawUtc = DiagnosticsOverlay.LastDrawUtc;
            snapshot.LastUpdateUtc = RuntimeDiagnostics.LastUpdateUtc;
            snapshot.LastHeartbeatUtc = State == null ? null : State.LastHeartbeatUtc;
            snapshot.FeatureCount = featureInfo.TotalFeatures;
            snapshot.EnabledFeatureCount = featureInfo.EnabledFeatures;
            snapshot.AppSettingsEnabledFeatureCount = ConfigService.CountAppSettingsEnabledFeatures();
            snapshot.FeatureSettingsEnabledFeatureCount = ConfigService.CountFeatureSettingsEnabledFeatures();
            snapshot.EffectiveEnabledFeatureCount = ConfigService.CountEffectiveEnabledFeatures();
            snapshot.FeatureCatalogCount = _featureCatalogCount;
            snapshot.ImplementedFeatureCount = _implementedFeatureCount;
            snapshot.VisibleFeatureCount = _visibleFeatureCount;
            snapshot.HotkeyVisibleFeatureCount = _hotkeyVisibleFeatureCount;
            snapshot.UserCategoryCounts = _userCategoryCounts;
            snapshot.CodeDomainCounts = _codeDomainCounts;
            snapshot.FeatureManagerUpdateCount = featureInfo.UpdateCount;
            snapshot.WorldGenDebugViewerConfiguredEnabled = ConfigService.AppSettings != null && ConfigService.AppSettings.DiagnosticsWorldGenDebugViewerEnabled;
            snapshot.DeveloperDebugCommandsConfiguredEnabled = ConfigService.AppSettings != null && ConfigService.AppSettings.DiagnosticsDeveloperDebugCommandsEnabled;
            snapshot.WorldGenDebugViewerSessionConfiguredEnabled = WorldGenDebugCompat.WorldGenSessionConfiguredEnabled;
            snapshot.DeveloperDebugCommandsSessionConfiguredEnabled = WorldGenDebugCompat.SessionConfiguredEnabled;
            snapshot.WorldGenDebugAttempted = WorldGenDebugCompat.Attempted;
            snapshot.WorldGenDebugFieldEnabled = WorldGenDebugCompat.Enabled;
            snapshot.WorldGenDebugStatus = WorldGenDebugCompat.Status;
            snapshot.WorldGenDebugMessage = WorldGenDebugCompat.Message;
            snapshot.WorldGenDebugFieldOwner = WorldGenDebugCompat.FieldOwner;
            snapshot.WorldGenDebugLastAttemptUtc = WorldGenDebugCompat.LastAttemptUtc;
            snapshot.IsInMainMenu = gameState.IsInMainMenu;
            snapshot.IsInWorld = gameState.IsInWorld;
            snapshot.GameInputAvailable = IsGameInputAvailable(gameState);
            snapshot.DiagnosticInputSkipped = RuntimeTargetingDiagnostics.DiagnosticInputSkipped;
            snapshot.DiagnosticInputGateStatus = RuntimeTargetingDiagnostics.DiagnosticInputGateStatus;
            snapshot.DiagnosticInputSkipReason = RuntimeTargetingDiagnostics.DiagnosticInputSkipReason;
            snapshot.DiagnosticInputSkipUtc = RuntimeTargetingDiagnostics.DiagnosticInputSkipUtc;
            snapshot.PlayerLife = gameState.Player == null ? 0 : gameState.Player.Life;
            snapshot.PlayerLifeMax = gameState.Player == null ? 0 : gameState.Player.LifeMax;
            snapshot.PlayerMana = gameState.Player == null ? 0 : gameState.Player.Mana;
            snapshot.PlayerManaMax = gameState.Player == null ? 0 : gameState.Player.ManaMax;
            snapshot.SelectedItemType = gameState.Inventory == null || gameState.Inventory.SelectedItem == null ? 0 : gameState.Inventory.SelectedItem.Type;
            snapshot.SelectedItemName = gameState.Inventory == null || gameState.Inventory.SelectedItem == null ? string.Empty : gameState.Inventory.SelectedItem.Name;
            snapshot.InventoryNonEmptyCount = gameState.Inventory == null ? 0 : gameState.Inventory.NonEmptyCount;
            snapshot.ActiveBuffCount = gameState.ActiveBuffs == null ? 0 : gameState.ActiveBuffs.Count;
            snapshot.ActiveNpcCount = gameState.Npcs == null ? 0 : gameState.Npcs.ActiveNpcCount;
            snapshot.TownNpcCount = gameState.Npcs == null ? 0 : gameState.Npcs.TownNpcCount;
            snapshot.HostileNpcCount = gameState.Npcs == null ? 0 : gameState.Npcs.HostileNpcCount;
            snapshot.CritterCount = gameState.Npcs == null ? 0 : gameState.Npcs.CritterCount;
            snapshot.LastGameStateReadUtc = gameState.LastReadUtc;
            snapshot.LastGameStateReadError = gameState.LastReadError;
            snapshot.LastGameStateInventoryProfile = GameStateReader.LastInventoryProfile.ToString();
            snapshot.LastGameStateNpcProfile = GameStateReader.LastNpcProfile.ToString();
            snapshot.LastGameStateTileProfile = GameStateReader.LastTileProfile.ToString();
        }
    }
}
